// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/flexprice/flexprice-go/v2/internal/utils"
	"github.com/flexprice/flexprice-go/v2/types"
)

type AttemptInvoicePaymentRequest struct {
	// Invoice ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (a *AttemptInvoicePaymentRequest) GetID() string {
	if a == nil {
		return ""
	}
	return a.ID
}

type AttemptInvoicePaymentResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	DtoSuccessResponse *types.DtoSuccessResponse
}

func (a AttemptInvoicePaymentResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AttemptInvoicePaymentResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AttemptInvoicePaymentResponse) GetHTTPMeta() types.HTTPMetadata {
	if a == nil {
		return types.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *AttemptInvoicePaymentResponse) GetDtoSuccessResponse() *types.DtoSuccessResponse {
	if a == nil {
		return nil
	}
	return a.DtoSuccessResponse
}
