// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/flexprice/flexprice-go/internal/utils"
	"github.com/flexprice/flexprice-go/types"
)

type CreatePlanResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// Created
	DtoPlanResponse *types.DtoPlanResponse
}

func (c CreatePlanResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreatePlanResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreatePlanResponse) GetHTTPMeta() types.HTTPMetadata {
	if c == nil {
		return types.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreatePlanResponse) GetDtoPlanResponse() *types.DtoPlanResponse {
	if c == nil {
		return nil
	}
	return c.DtoPlanResponse
}
