// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/flexprice/flexprice-go/internal/utils"
	"github.com/flexprice/flexprice-go/types"
)

type CreateEntityIntegrationMappingResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// Created
	DtoEntityIntegrationMappingResponse *types.DtoEntityIntegrationMappingResponse
}

func (c CreateEntityIntegrationMappingResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateEntityIntegrationMappingResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateEntityIntegrationMappingResponse) GetHTTPMeta() types.HTTPMetadata {
	if c == nil {
		return types.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateEntityIntegrationMappingResponse) GetDtoEntityIntegrationMappingResponse() *types.DtoEntityIntegrationMappingResponse {
	if c == nil {
		return nil
	}
	return c.DtoEntityIntegrationMappingResponse
}
