// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/flexprice/flexprice-go/v2/internal/utils"
	"github.com/flexprice/flexprice-go/v2/types"
)

type CreateOrUpdateIntegrationRequest struct {
	// Integration provider
	Provider string `pathParam:"style=simple,explode=false,name=provider"`
	// Integration creation request
	Body types.DtoCreateIntegrationRequest `request:"mediaType=application/json"`
}

func (c *CreateOrUpdateIntegrationRequest) GetProvider() string {
	if c == nil {
		return ""
	}
	return c.Provider
}

func (c *CreateOrUpdateIntegrationRequest) GetBody() types.DtoCreateIntegrationRequest {
	if c == nil {
		return types.DtoCreateIntegrationRequest{}
	}
	return c.Body
}

type CreateOrUpdateIntegrationResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// Created
	DtoSecretResponse *types.DtoSecretResponse
}

func (c CreateOrUpdateIntegrationResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateOrUpdateIntegrationResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateOrUpdateIntegrationResponse) GetHTTPMeta() types.HTTPMetadata {
	if c == nil {
		return types.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateOrUpdateIntegrationResponse) GetDtoSecretResponse() *types.DtoSecretResponse {
	if c == nil {
		return nil
	}
	return c.DtoSecretResponse
}
