// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/flexprice/flexprice-go/internal/utils"
	"github.com/flexprice/flexprice-go/types"
)

type CreateCouponResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// Created
	DtoCouponResponse *types.DtoCouponResponse
}

func (c CreateCouponResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateCouponResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateCouponResponse) GetHTTPMeta() types.HTTPMetadata {
	if c == nil {
		return types.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateCouponResponse) GetDtoCouponResponse() *types.DtoCouponResponse {
	if c == nil {
		return nil
	}
	return c.DtoCouponResponse
}
