// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/flexprice/flexprice-go/internal/utils"
	"github.com/flexprice/flexprice-go/types"
)

type CreateInvoiceResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// Created
	DtoInvoiceResponse *types.DtoInvoiceResponse
}

func (c CreateInvoiceResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateInvoiceResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateInvoiceResponse) GetHTTPMeta() types.HTTPMetadata {
	if c == nil {
		return types.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateInvoiceResponse) GetDtoInvoiceResponse() *types.DtoInvoiceResponse {
	if c == nil {
		return nil
	}
	return c.DtoInvoiceResponse
}
