// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/flexprice/flexprice-go/internal/utils"
	"github.com/flexprice/flexprice-go/types"
)

type CreateCustomerResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// Created
	DtoCustomerResponse *types.DtoCustomerResponse
}

func (c CreateCustomerResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateCustomerResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateCustomerResponse) GetHTTPMeta() types.HTTPMetadata {
	if c == nil {
		return types.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateCustomerResponse) GetDtoCustomerResponse() *types.DtoCustomerResponse {
	if c == nil {
		return nil
	}
	return c.DtoCustomerResponse
}
