// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/flexprice/flexprice-go/v2/internal/utils"
	"github.com/flexprice/flexprice-go/v2/types"
)

type CreateCostsheetResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// Created costsheet
	DtoCreateCostsheetResponse *types.DtoCreateCostsheetResponse
}

func (c CreateCostsheetResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateCostsheetResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateCostsheetResponse) GetHTTPMeta() types.HTTPMetadata {
	if c == nil {
		return types.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateCostsheetResponse) GetDtoCreateCostsheetResponse() *types.DtoCreateCostsheetResponse {
	if c == nil {
		return nil
	}
	return c.DtoCreateCostsheetResponse
}
