// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/flexprice/flexprice-go/types"
)

type DeleteGroupRequest struct {
	// Group ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (d *DeleteGroupRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

type DeleteGroupResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
}

func (d *DeleteGroupResponse) GetHTTPMeta() types.HTTPMetadata {
	if d == nil {
		return types.HTTPMetadata{}
	}
	return d.HTTPMeta
}
