// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/flexprice/flexprice-go/types"
)

type DeleteCustomerRequest struct {
	// Customer ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (d *DeleteCustomerRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

type DeleteCustomerResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
}

func (d *DeleteCustomerResponse) GetHTTPMeta() types.HTTPMetadata {
	if d == nil {
		return types.HTTPMetadata{}
	}
	return d.HTTPMeta
}
