// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/flexprice/flexprice-go/v2/internal/utils"
	"github.com/flexprice/flexprice-go/v2/types"
)

type DeleteAddonRequest struct {
	// Addon ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (d *DeleteAddonRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

type DeleteAddonResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	DtoSuccessResponse *types.DtoSuccessResponse
}

func (d DeleteAddonResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteAddonResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeleteAddonResponse) GetHTTPMeta() types.HTTPMetadata {
	if d == nil {
		return types.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeleteAddonResponse) GetDtoSuccessResponse() *types.DtoSuccessResponse {
	if d == nil {
		return nil
	}
	return d.DtoSuccessResponse
}
