// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/flexprice/flexprice-go/v2/types"
)

type DeleteIntegrationRequest struct {
	// Integration ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (d *DeleteIntegrationRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

type DeleteIntegrationResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
}

func (d *DeleteIntegrationResponse) GetHTTPMeta() types.HTTPMetadata {
	if d == nil {
		return types.HTTPMetadata{}
	}
	return d.HTTPMeta
}
