// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/flexprice/flexprice-go/v2/internal/utils"
	"github.com/flexprice/flexprice-go/v2/types"
)

type FinalizeInvoiceRequest struct {
	// Invoice ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (f *FinalizeInvoiceRequest) GetID() string {
	if f == nil {
		return ""
	}
	return f.ID
}

type FinalizeInvoiceResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	DtoSuccessResponse *types.DtoSuccessResponse
}

func (f FinalizeInvoiceResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FinalizeInvoiceResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FinalizeInvoiceResponse) GetHTTPMeta() types.HTTPMetadata {
	if f == nil {
		return types.HTTPMetadata{}
	}
	return f.HTTPMeta
}

func (f *FinalizeInvoiceResponse) GetDtoSuccessResponse() *types.DtoSuccessResponse {
	if f == nil {
		return nil
	}
	return f.DtoSuccessResponse
}
