// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/flexprice/flexprice-go/v2/internal/utils"
	"github.com/flexprice/flexprice-go/v2/types"
)

type GetCostsheetRequest struct {
	// Costsheet ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Comma-separated list of fields to expand (e.g., 'prices')
	Expand *string `queryParam:"style=form,explode=true,name=expand"`
}

func (g *GetCostsheetRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetCostsheetRequest) GetExpand() *string {
	if g == nil {
		return nil
	}
	return g.Expand
}

type GetCostsheetResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// Costsheet details
	DtoGetCostsheetResponse *types.DtoGetCostsheetResponse
}

func (g GetCostsheetResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetCostsheetResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetCostsheetResponse) GetHTTPMeta() types.HTTPMetadata {
	if g == nil {
		return types.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetCostsheetResponse) GetDtoGetCostsheetResponse() *types.DtoGetCostsheetResponse {
	if g == nil {
		return nil
	}
	return g.DtoGetCostsheetResponse
}
