// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/flexprice/flexprice-go/v2/internal/utils"
	"github.com/flexprice/flexprice-go/v2/types"
)

type GetHuggingfaceInferenceDataResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	DtoGetHuggingFaceBillingDataResponse *types.DtoGetHuggingFaceBillingDataResponse
}

func (g GetHuggingfaceInferenceDataResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetHuggingfaceInferenceDataResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetHuggingfaceInferenceDataResponse) GetHTTPMeta() types.HTTPMetadata {
	if g == nil {
		return types.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetHuggingfaceInferenceDataResponse) GetDtoGetHuggingFaceBillingDataResponse() *types.DtoGetHuggingFaceBillingDataResponse {
	if g == nil {
		return nil
	}
	return g.DtoGetHuggingFaceBillingDataResponse
}
