// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/flexprice/flexprice-go/v2/internal/utils"
	"github.com/flexprice/flexprice-go/v2/types"
)

type GetPaymentRequest struct {
	// Payment ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetPaymentRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetPaymentResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// Payment details
	DtoPaymentResponse *types.DtoPaymentResponse
}

func (g GetPaymentResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetPaymentResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetPaymentResponse) GetHTTPMeta() types.HTTPMetadata {
	if g == nil {
		return types.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetPaymentResponse) GetDtoPaymentResponse() *types.DtoPaymentResponse {
	if g == nil {
		return nil
	}
	return g.DtoPaymentResponse
}
