// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/flexprice/flexprice-go/v2/internal/utils"
	"github.com/flexprice/flexprice-go/v2/types"
)

type GetPriceByLookupKeyRequest struct {
	// Lookup key
	LookupKey string `pathParam:"style=simple,explode=false,name=lookup_key"`
}

func (g *GetPriceByLookupKeyRequest) GetLookupKey() string {
	if g == nil {
		return ""
	}
	return g.LookupKey
}

type GetPriceByLookupKeyResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	DtoPriceResponse *types.DtoPriceResponse
}

func (g GetPriceByLookupKeyResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetPriceByLookupKeyResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetPriceByLookupKeyResponse) GetHTTPMeta() types.HTTPMetadata {
	if g == nil {
		return types.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetPriceByLookupKeyResponse) GetDtoPriceResponse() *types.DtoPriceResponse {
	if g == nil {
		return nil
	}
	return g.DtoPriceResponse
}
