// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/flexprice/flexprice-go/internal/utils"
	"github.com/flexprice/flexprice-go/types"
)

type GetPriceUnitRequest struct {
	// Price unit ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetPriceUnitRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetPriceUnitResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	DtoPriceUnitResponse *types.DtoPriceUnitResponse
}

func (g GetPriceUnitResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetPriceUnitResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetPriceUnitResponse) GetHTTPMeta() types.HTTPMetadata {
	if g == nil {
		return types.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetPriceUnitResponse) GetDtoPriceUnitResponse() *types.DtoPriceUnitResponse {
	if g == nil {
		return nil
	}
	return g.DtoPriceUnitResponse
}
