// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/flexprice/flexprice-go/internal/utils"
	"github.com/flexprice/flexprice-go/types"
)

type GetPriceRequest struct {
	// Price ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetPriceRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetPriceResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	DtoPriceResponse *types.DtoPriceResponse
}

func (g GetPriceResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetPriceResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetPriceResponse) GetHTTPMeta() types.HTTPMetadata {
	if g == nil {
		return types.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetPriceResponse) GetDtoPriceResponse() *types.DtoPriceResponse {
	if g == nil {
		return nil
	}
	return g.DtoPriceResponse
}
