// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/flexprice/flexprice-go/internal/utils"
	"github.com/flexprice/flexprice-go/types"
)

type GetPlanEntitlementsRequest struct {
	// Plan ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetPlanEntitlementsRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetPlanEntitlementsResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	DtoPlanResponse *types.DtoPlanResponse
}

func (g GetPlanEntitlementsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetPlanEntitlementsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetPlanEntitlementsResponse) GetHTTPMeta() types.HTTPMetadata {
	if g == nil {
		return types.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetPlanEntitlementsResponse) GetDtoPlanResponse() *types.DtoPlanResponse {
	if g == nil {
		return nil
	}
	return g.DtoPlanResponse
}
