// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/flexprice/flexprice-go/v2/internal/utils"
	"github.com/flexprice/flexprice-go/v2/types"
)

type GetScheduledTaskRequest struct {
	// Scheduled Task ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetScheduledTaskRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetScheduledTaskResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	DtoScheduledTaskResponse *types.DtoScheduledTaskResponse
}

func (g GetScheduledTaskResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetScheduledTaskResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetScheduledTaskResponse) GetHTTPMeta() types.HTTPMetadata {
	if g == nil {
		return types.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetScheduledTaskResponse) GetDtoScheduledTaskResponse() *types.DtoScheduledTaskResponse {
	if g == nil {
		return nil
	}
	return g.DtoScheduledTaskResponse
}
