// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/flexprice/flexprice-go/v2/internal/utils"
	"github.com/flexprice/flexprice-go/v2/types"
)

type GetSubscriptionAddonAssociationsRequest struct {
	// Subscription ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetSubscriptionAddonAssociationsRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetSubscriptionAddonAssociationsResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	DtoAddonAssociationResponses []types.DtoAddonAssociationResponse
}

func (g GetSubscriptionAddonAssociationsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetSubscriptionAddonAssociationsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetSubscriptionAddonAssociationsResponse) GetHTTPMeta() types.HTTPMetadata {
	if g == nil {
		return types.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetSubscriptionAddonAssociationsResponse) GetDtoAddonAssociationResponses() []types.DtoAddonAssociationResponse {
	if g == nil {
		return nil
	}
	return g.DtoAddonAssociationResponses
}
