// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/flexprice/flexprice-go/v2/internal/utils"
	"github.com/flexprice/flexprice-go/v2/types"
)

type GetSubscriptionUpcomingGrantsRequest struct {
	// Subscription ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetSubscriptionUpcomingGrantsRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetSubscriptionUpcomingGrantsResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	DtoListCreditGrantApplicationsResponse *types.DtoListCreditGrantApplicationsResponse
}

func (g GetSubscriptionUpcomingGrantsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetSubscriptionUpcomingGrantsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetSubscriptionUpcomingGrantsResponse) GetHTTPMeta() types.HTTPMetadata {
	if g == nil {
		return types.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetSubscriptionUpcomingGrantsResponse) GetDtoListCreditGrantApplicationsResponse() *types.DtoListCreditGrantApplicationsResponse {
	if g == nil {
		return nil
	}
	return g.DtoListCreditGrantApplicationsResponse
}
