// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/flexprice/flexprice-go/v2/internal/utils"
	"github.com/flexprice/flexprice-go/v2/types"
)

type GetTaskResultRequest struct {
	// Workflow ID
	WorkflowID string `queryParam:"style=form,explode=true,name=workflow_id"`
}

func (g *GetTaskResultRequest) GetWorkflowID() string {
	if g == nil {
		return ""
	}
	return g.WorkflowID
}

type GetTaskResultResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	ModelsTemporalWorkflowResult *types.ModelsTemporalWorkflowResult
}

func (g GetTaskResultResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetTaskResultResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetTaskResultResponse) GetHTTPMeta() types.HTTPMetadata {
	if g == nil {
		return types.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetTaskResultResponse) GetModelsTemporalWorkflowResult() *types.ModelsTemporalWorkflowResult {
	if g == nil {
		return nil
	}
	return g.ModelsTemporalWorkflowResult
}
