// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/flexprice/flexprice-go/v2/internal/utils"
	"github.com/flexprice/flexprice-go/v2/types"
)

type GetTaxAssociationRequest struct {
	// Tax Config ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetTaxAssociationRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetTaxAssociationResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	DtoTaxAssociationResponse *types.DtoTaxAssociationResponse
}

func (g GetTaxAssociationResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetTaxAssociationResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetTaxAssociationResponse) GetHTTPMeta() types.HTTPMetadata {
	if g == nil {
		return types.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetTaxAssociationResponse) GetDtoTaxAssociationResponse() *types.DtoTaxAssociationResponse {
	if g == nil {
		return nil
	}
	return g.DtoTaxAssociationResponse
}
