// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/flexprice/flexprice-go/internal/utils"
	"github.com/flexprice/flexprice-go/types"
)

type GetUserInfoResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	DtoUserResponse *types.DtoUserResponse
}

func (g GetUserInfoResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetUserInfoResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetUserInfoResponse) GetHTTPMeta() types.HTTPMetadata {
	if g == nil {
		return types.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetUserInfoResponse) GetDtoUserResponse() *types.DtoUserResponse {
	if g == nil {
		return nil
	}
	return g.DtoUserResponse
}
