// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/flexprice/flexprice-go/internal/utils"
	"github.com/flexprice/flexprice-go/types"
)

type GetWalletRequest struct {
	// Wallet ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetWalletRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetWalletResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	DtoWalletResponse *types.DtoWalletResponse
}

func (g GetWalletResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetWalletResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetWalletResponse) GetHTTPMeta() types.HTTPMetadata {
	if g == nil {
		return types.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetWalletResponse) GetDtoWalletResponse() *types.DtoWalletResponse {
	if g == nil {
		return nil
	}
	return g.DtoWalletResponse
}
