// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/flexprice/flexprice-go/v2/internal/utils"
	"github.com/flexprice/flexprice-go/v2/types"
)

type HandleChargebeeWebhookRequest struct {
	// Tenant ID
	TenantID string `pathParam:"style=simple,explode=false,name=tenant_id"`
	// Environment ID
	EnvironmentID string `pathParam:"style=simple,explode=false,name=environment_id"`
}

func (h *HandleChargebeeWebhookRequest) GetTenantID() string {
	if h == nil {
		return ""
	}
	return h.TenantID
}

func (h *HandleChargebeeWebhookRequest) GetEnvironmentID() string {
	if h == nil {
		return ""
	}
	return h.EnvironmentID
}

type HandleChargebeeWebhookResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// Webhook processed successfully
	Object map[string]any
}

func (h HandleChargebeeWebhookResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(h, "", false)
}

func (h *HandleChargebeeWebhookResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &h, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (h *HandleChargebeeWebhookResponse) GetHTTPMeta() types.HTTPMetadata {
	if h == nil {
		return types.HTTPMetadata{}
	}
	return h.HTTPMeta
}

func (h *HandleChargebeeWebhookResponse) GetObject() map[string]any {
	if h == nil {
		return nil
	}
	return h.Object
}
