// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/flexprice/flexprice-go/v2/internal/utils"
	"github.com/flexprice/flexprice-go/v2/types"
)

type ListLinkedIntegrationsResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	DtoLinkedIntegrationsResponse *types.DtoLinkedIntegrationsResponse
}

func (l ListLinkedIntegrationsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListLinkedIntegrationsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListLinkedIntegrationsResponse) GetHTTPMeta() types.HTTPMetadata {
	if l == nil {
		return types.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListLinkedIntegrationsResponse) GetDtoLinkedIntegrationsResponse() *types.DtoLinkedIntegrationsResponse {
	if l == nil {
		return nil
	}
	return l.DtoLinkedIntegrationsResponse
}
