// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/flexprice/flexprice-go/v2/internal/utils"
	"github.com/flexprice/flexprice-go/v2/types"
)

type PauseSubscriptionRequest struct {
	// Subscription ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Pause subscription request
	Body types.DtoPauseSubscriptionRequest `request:"mediaType=application/json"`
}

func (p *PauseSubscriptionRequest) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PauseSubscriptionRequest) GetBody() types.DtoPauseSubscriptionRequest {
	if p == nil {
		return types.DtoPauseSubscriptionRequest{}
	}
	return p.Body
}

type PauseSubscriptionResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	DtoSubscriptionPauseResponse *types.DtoSubscriptionPauseResponse
}

func (p PauseSubscriptionResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PauseSubscriptionResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PauseSubscriptionResponse) GetHTTPMeta() types.HTTPMetadata {
	if p == nil {
		return types.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PauseSubscriptionResponse) GetDtoSubscriptionPauseResponse() *types.DtoSubscriptionPauseResponse {
	if p == nil {
		return nil
	}
	return p.DtoSubscriptionPauseResponse
}
