// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/flexprice/flexprice-go/internal/utils"
	"github.com/flexprice/flexprice-go/types"
)

type QueryCostsheetResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// Paginated costsheets
	DtoListCostsheetResponse *types.DtoListCostsheetResponse
}

func (q QueryCostsheetResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(q, "", false)
}

func (q *QueryCostsheetResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &q, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (q *QueryCostsheetResponse) GetHTTPMeta() types.HTTPMetadata {
	if q == nil {
		return types.HTTPMetadata{}
	}
	return q.HTTPMeta
}

func (q *QueryCostsheetResponse) GetDtoListCostsheetResponse() *types.DtoListCostsheetResponse {
	if q == nil {
		return nil
	}
	return q.DtoListCostsheetResponse
}
