// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/flexprice/flexprice-go/v2/internal/utils"
	"github.com/flexprice/flexprice-go/v2/types"
)

type QueryFeatureResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	DtoListFeaturesResponse *types.DtoListFeaturesResponse
}

func (q QueryFeatureResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(q, "", false)
}

func (q *QueryFeatureResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &q, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (q *QueryFeatureResponse) GetHTTPMeta() types.HTTPMetadata {
	if q == nil {
		return types.HTTPMetadata{}
	}
	return q.HTTPMeta
}

func (q *QueryFeatureResponse) GetDtoListFeaturesResponse() *types.DtoListFeaturesResponse {
	if q == nil {
		return nil
	}
	return q.DtoListFeaturesResponse
}
