// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/flexprice/flexprice-go/v2/internal/utils"
	"github.com/flexprice/flexprice-go/v2/types"
)

type QueryWorkflowResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	DtoListWorkflowsResponse *types.DtoListWorkflowsResponse
}

func (q QueryWorkflowResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(q, "", false)
}

func (q *QueryWorkflowResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &q, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (q *QueryWorkflowResponse) GetHTTPMeta() types.HTTPMetadata {
	if q == nil {
		return types.HTTPMetadata{}
	}
	return q.HTTPMeta
}

func (q *QueryWorkflowResponse) GetDtoListWorkflowsResponse() *types.DtoListWorkflowsResponse {
	if q == nil {
		return nil
	}
	return q.DtoListWorkflowsResponse
}
