// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/flexprice/flexprice-go/internal/utils"
	"github.com/flexprice/flexprice-go/types"
)

type QueryInvoiceResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	DtoListInvoicesResponse *types.DtoListInvoicesResponse
}

func (q QueryInvoiceResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(q, "", false)
}

func (q *QueryInvoiceResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &q, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (q *QueryInvoiceResponse) GetHTTPMeta() types.HTTPMetadata {
	if q == nil {
		return types.HTTPMetadata{}
	}
	return q.HTTPMeta
}

func (q *QueryInvoiceResponse) GetDtoListInvoicesResponse() *types.DtoListInvoicesResponse {
	if q == nil {
		return nil
	}
	return q.DtoListInvoicesResponse
}
