// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/flexprice/flexprice-go/v2/internal/utils"
	"github.com/flexprice/flexprice-go/v2/types"
)

type QueryWalletTransactionResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	DtoListWalletTransactionsResponse *types.DtoListWalletTransactionsResponse
}

func (q QueryWalletTransactionResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(q, "", false)
}

func (q *QueryWalletTransactionResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &q, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (q *QueryWalletTransactionResponse) GetHTTPMeta() types.HTTPMetadata {
	if q == nil {
		return types.HTTPMetadata{}
	}
	return q.HTTPMeta
}

func (q *QueryWalletTransactionResponse) GetDtoListWalletTransactionsResponse() *types.DtoListWalletTransactionsResponse {
	if q == nil {
		return nil
	}
	return q.DtoListWalletTransactionsResponse
}
