// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/flexprice/flexprice-go/internal/utils"
	"github.com/flexprice/flexprice-go/types"
)

type QueryEntitlementResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	DtoListEntitlementsResponse *types.DtoListEntitlementsResponse
}

func (q QueryEntitlementResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(q, "", false)
}

func (q *QueryEntitlementResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &q, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (q *QueryEntitlementResponse) GetHTTPMeta() types.HTTPMetadata {
	if q == nil {
		return types.HTTPMetadata{}
	}
	return q.HTTPMeta
}

func (q *QueryEntitlementResponse) GetDtoListEntitlementsResponse() *types.DtoListEntitlementsResponse {
	if q == nil {
		return nil
	}
	return q.DtoListEntitlementsResponse
}
