// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/flexprice/flexprice-go/internal/utils"
	"github.com/flexprice/flexprice-go/types"
)

type QueryAlertLogResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	DtoListAlertLogsResponse *types.DtoListAlertLogsResponse
}

func (q QueryAlertLogResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(q, "", false)
}

func (q *QueryAlertLogResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &q, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (q *QueryAlertLogResponse) GetHTTPMeta() types.HTTPMetadata {
	if q == nil {
		return types.HTTPMetadata{}
	}
	return q.HTTPMeta
}

func (q *QueryAlertLogResponse) GetDtoListAlertLogsResponse() *types.DtoListAlertLogsResponse {
	if q == nil {
		return nil
	}
	return q.DtoListAlertLogsResponse
}
