// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/flexprice/flexprice-go/internal/utils"
	"github.com/flexprice/flexprice-go/types"
)

type ResumeSubscriptionRequest struct {
	// Subscription ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Resume subscription request
	Body types.DtoResumeSubscriptionRequest `request:"mediaType=application/json"`
}

func (r *ResumeSubscriptionRequest) GetID() string {
	if r == nil {
		return ""
	}
	return r.ID
}

func (r *ResumeSubscriptionRequest) GetBody() types.DtoResumeSubscriptionRequest {
	if r == nil {
		return types.DtoResumeSubscriptionRequest{}
	}
	return r.Body
}

type ResumeSubscriptionResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	DtoSubscriptionPauseResponse *types.DtoSubscriptionPauseResponse
}

func (r ResumeSubscriptionResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ResumeSubscriptionResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *ResumeSubscriptionResponse) GetHTTPMeta() types.HTTPMetadata {
	if r == nil {
		return types.HTTPMetadata{}
	}
	return r.HTTPMeta
}

func (r *ResumeSubscriptionResponse) GetDtoSubscriptionPauseResponse() *types.DtoSubscriptionPauseResponse {
	if r == nil {
		return nil
	}
	return r.DtoSubscriptionPauseResponse
}
