// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/flexprice/flexprice-go/internal/utils"
	"github.com/flexprice/flexprice-go/types"
)

type TriggerInvoiceCommsWebhookRequest struct {
	// Invoice ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (t *TriggerInvoiceCommsWebhookRequest) GetID() string {
	if t == nil {
		return ""
	}
	return t.ID
}

type TriggerInvoiceCommsWebhookResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	DtoSuccessResponse *types.DtoSuccessResponse
}

func (t TriggerInvoiceCommsWebhookResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TriggerInvoiceCommsWebhookResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TriggerInvoiceCommsWebhookResponse) GetHTTPMeta() types.HTTPMetadata {
	if t == nil {
		return types.HTTPMetadata{}
	}
	return t.HTTPMeta
}

func (t *TriggerInvoiceCommsWebhookResponse) GetDtoSuccessResponse() *types.DtoSuccessResponse {
	if t == nil {
		return nil
	}
	return t.DtoSuccessResponse
}
