// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/flexprice/flexprice-go/v2/internal/utils"
	"github.com/flexprice/flexprice-go/v2/types"
)

type UpdateFeatureRequest struct {
	// Feature ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Feature update data
	Body types.DtoUpdateFeatureRequest `request:"mediaType=application/json"`
}

func (u *UpdateFeatureRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateFeatureRequest) GetBody() types.DtoUpdateFeatureRequest {
	if u == nil {
		return types.DtoUpdateFeatureRequest{}
	}
	return u.Body
}

type UpdateFeatureResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	DtoFeatureResponse *types.DtoFeatureResponse
}

func (u UpdateFeatureResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateFeatureResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateFeatureResponse) GetHTTPMeta() types.HTTPMetadata {
	if u == nil {
		return types.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateFeatureResponse) GetDtoFeatureResponse() *types.DtoFeatureResponse {
	if u == nil {
		return nil
	}
	return u.DtoFeatureResponse
}
