// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/flexprice/flexprice-go/internal/utils"
	"github.com/flexprice/flexprice-go/types"
)

type UpdatePriceRequest struct {
	// Price ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Price configuration
	Body types.DtoUpdatePriceRequest `request:"mediaType=application/json"`
}

func (u *UpdatePriceRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdatePriceRequest) GetBody() types.DtoUpdatePriceRequest {
	if u == nil {
		return types.DtoUpdatePriceRequest{}
	}
	return u.Body
}

type UpdatePriceResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	DtoPriceResponse *types.DtoPriceResponse
}

func (u UpdatePriceResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdatePriceResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdatePriceResponse) GetHTTPMeta() types.HTTPMetadata {
	if u == nil {
		return types.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdatePriceResponse) GetDtoPriceResponse() *types.DtoPriceResponse {
	if u == nil {
		return nil
	}
	return u.DtoPriceResponse
}
