// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/flexprice/flexprice-go/v2/internal/utils"
	"github.com/flexprice/flexprice-go/v2/types"
)

type UpdateAddonRequest struct {
	// Addon ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Update Addon Request
	Body types.DtoUpdateAddonRequest `request:"mediaType=application/json"`
}

func (u *UpdateAddonRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateAddonRequest) GetBody() types.DtoUpdateAddonRequest {
	if u == nil {
		return types.DtoUpdateAddonRequest{}
	}
	return u.Body
}

type UpdateAddonResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	DtoAddonResponse *types.DtoAddonResponse
}

func (u UpdateAddonResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateAddonResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateAddonResponse) GetHTTPMeta() types.HTTPMetadata {
	if u == nil {
		return types.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateAddonResponse) GetDtoAddonResponse() *types.DtoAddonResponse {
	if u == nil {
		return nil
	}
	return u.DtoAddonResponse
}
