// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/flexprice/flexprice-go/internal/utils"
	"github.com/flexprice/flexprice-go/types"
)

type UpdateCreditGrantRequest struct {
	// Credit Grant ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Credit Grant configuration
	Body types.DtoUpdateCreditGrantRequest `request:"mediaType=application/json"`
}

func (u *UpdateCreditGrantRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateCreditGrantRequest) GetBody() types.DtoUpdateCreditGrantRequest {
	if u == nil {
		return types.DtoUpdateCreditGrantRequest{}
	}
	return u.Body
}

type UpdateCreditGrantResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	DtoCreditGrantResponse *types.DtoCreditGrantResponse
}

func (u UpdateCreditGrantResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateCreditGrantResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateCreditGrantResponse) GetHTTPMeta() types.HTTPMetadata {
	if u == nil {
		return types.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateCreditGrantResponse) GetDtoCreditGrantResponse() *types.DtoCreditGrantResponse {
	if u == nil {
		return nil
	}
	return u.DtoCreditGrantResponse
}
