// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/flexprice/flexprice-go/internal/utils"
	"github.com/flexprice/flexprice-go/types"
)

type UpdateTaxRateRequest struct {
	// Tax rate ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Tax rate to update
	Body types.DtoUpdateTaxRateRequest `request:"mediaType=application/json"`
}

func (u *UpdateTaxRateRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateTaxRateRequest) GetBody() types.DtoUpdateTaxRateRequest {
	if u == nil {
		return types.DtoUpdateTaxRateRequest{}
	}
	return u.Body
}

type UpdateTaxRateResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	DtoTaxRateResponse *types.DtoTaxRateResponse
}

func (u UpdateTaxRateResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateTaxRateResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateTaxRateResponse) GetHTTPMeta() types.HTTPMetadata {
	if u == nil {
		return types.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateTaxRateResponse) GetDtoTaxRateResponse() *types.DtoTaxRateResponse {
	if u == nil {
		return nil
	}
	return u.DtoTaxRateResponse
}
