// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/flexprice/flexprice-go/v2/internal/utils"
	"github.com/flexprice/flexprice-go/v2/types"
)

type UpdateCouponRequest struct {
	// Coupon ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Coupon update request
	Body types.DtoUpdateCouponRequest `request:"mediaType=application/json"`
}

func (u *UpdateCouponRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateCouponRequest) GetBody() types.DtoUpdateCouponRequest {
	if u == nil {
		return types.DtoUpdateCouponRequest{}
	}
	return u.Body
}

type UpdateCouponResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	DtoCouponResponse *types.DtoCouponResponse
}

func (u UpdateCouponResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateCouponResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateCouponResponse) GetHTTPMeta() types.HTTPMetadata {
	if u == nil {
		return types.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateCouponResponse) GetDtoCouponResponse() *types.DtoCouponResponse {
	if u == nil {
		return nil
	}
	return u.DtoCouponResponse
}
