// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/flexprice/flexprice-go/internal/utils"
	"github.com/flexprice/flexprice-go/types"
)

type UpdateScheduledTaskRequest struct {
	// Scheduled Task ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Update request (enabled: true/false to pause/resume)
	Body types.DtoUpdateScheduledTaskRequest `request:"mediaType=application/json"`
}

func (u *UpdateScheduledTaskRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateScheduledTaskRequest) GetBody() types.DtoUpdateScheduledTaskRequest {
	if u == nil {
		return types.DtoUpdateScheduledTaskRequest{}
	}
	return u.Body
}

type UpdateScheduledTaskResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	DtoScheduledTaskResponse *types.DtoScheduledTaskResponse
}

func (u UpdateScheduledTaskResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateScheduledTaskResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateScheduledTaskResponse) GetHTTPMeta() types.HTTPMetadata {
	if u == nil {
		return types.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateScheduledTaskResponse) GetDtoScheduledTaskResponse() *types.DtoScheduledTaskResponse {
	if u == nil {
		return nil
	}
	return u.DtoScheduledTaskResponse
}
