// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flexprice/flexprice-go/internal/utils"
	"github.com/flexprice/flexprice-go/models/components"
)

type ActivateSubscriptionRequest struct {
	// Subscription ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Activate Draft Subscription Request
	Body components.DtoActivateDraftSubscriptionRequest `request:"mediaType=application/json"`
}

func (a *ActivateSubscriptionRequest) GetID() string {
	if a == nil {
		return ""
	}
	return a.ID
}

func (a *ActivateSubscriptionRequest) GetBody() components.DtoActivateDraftSubscriptionRequest {
	if a == nil {
		return components.DtoActivateDraftSubscriptionRequest{}
	}
	return a.Body
}

type ActivateSubscriptionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	DtoSubscriptionResponse *components.DtoSubscriptionResponse
}

func (a ActivateSubscriptionResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *ActivateSubscriptionResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *ActivateSubscriptionResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *ActivateSubscriptionResponse) GetDtoSubscriptionResponse() *components.DtoSubscriptionResponse {
	if a == nil {
		return nil
	}
	return a.DtoSubscriptionResponse
}
