// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flexprice/flexprice-go/internal/utils"
	"github.com/flexprice/flexprice-go/models/components"
)

type CreatePricesBulkResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Created
	DtoCreateBulkPriceResponse *components.DtoCreateBulkPriceResponse
}

func (c CreatePricesBulkResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreatePricesBulkResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreatePricesBulkResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreatePricesBulkResponse) GetDtoCreateBulkPriceResponse() *components.DtoCreateBulkPriceResponse {
	if c == nil {
		return nil
	}
	return c.DtoCreateBulkPriceResponse
}
