// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flexprice/flexprice-go/internal/utils"
	"github.com/flexprice/flexprice-go/models/components"
)

type CreateFeatureResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Created
	DtoFeatureResponse *components.DtoFeatureResponse
}

func (c CreateFeatureResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateFeatureResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateFeatureResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateFeatureResponse) GetDtoFeatureResponse() *components.DtoFeatureResponse {
	if c == nil {
		return nil
	}
	return c.DtoFeatureResponse
}
