// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flexprice/flexprice-go/internal/utils"
	"github.com/flexprice/flexprice-go/models/components"
)

type CreateTaxAssociationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	DtoTaxAssociationResponse *components.DtoTaxAssociationResponse
}

func (c CreateTaxAssociationResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateTaxAssociationResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateTaxAssociationResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateTaxAssociationResponse) GetDtoTaxAssociationResponse() *components.DtoTaxAssociationResponse {
	if c == nil {
		return nil
	}
	return c.DtoTaxAssociationResponse
}
