// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flexprice/flexprice-go/internal/utils"
	"github.com/flexprice/flexprice-go/models/components"
)

type CreateCreditNoteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Created
	DtoCreditNoteResponse *components.DtoCreditNoteResponse
}

func (c CreateCreditNoteResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateCreditNoteResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateCreditNoteResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateCreditNoteResponse) GetDtoCreditNoteResponse() *components.DtoCreditNoteResponse {
	if c == nil {
		return nil
	}
	return c.DtoCreditNoteResponse
}
