// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flexprice/flexprice-go/internal/utils"
	"github.com/flexprice/flexprice-go/models/components"
)

type CreateUserResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Created
	DtoUserResponse *components.DtoUserResponse
}

func (c CreateUserResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateUserResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateUserResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateUserResponse) GetDtoUserResponse() *components.DtoUserResponse {
	if c == nil {
		return nil
	}
	return c.DtoUserResponse
}
