// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flexprice/flexprice-go/internal/utils"
	"github.com/flexprice/flexprice-go/models/components"
)

type CreateEntitlementResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Created
	DtoEntitlementResponse *components.DtoEntitlementResponse
}

func (c CreateEntitlementResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateEntitlementResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateEntitlementResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateEntitlementResponse) GetDtoEntitlementResponse() *components.DtoEntitlementResponse {
	if c == nil {
		return nil
	}
	return c.DtoEntitlementResponse
}
