// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flexprice/flexprice-go/models/components"
)

type DeleteAPIKeyRequest struct {
	// API key ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (d *DeleteAPIKeyRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

type DeleteAPIKeyResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (d *DeleteAPIKeyResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}
