// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flexprice/flexprice-go/internal/utils"
	"github.com/flexprice/flexprice-go/models/components"
)

type DeleteCouponRequest struct {
	// Coupon ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (d *DeleteCouponRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

type DeleteCouponResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	Object map[string]string
}

func (d DeleteCouponResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteCouponResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeleteCouponResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeleteCouponResponse) GetObject() map[string]string {
	if d == nil {
		return nil
	}
	return d.Object
}
