// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flexprice/flexprice-go/internal/utils"
	"github.com/flexprice/flexprice-go/models/components"
)

type GetCustomerEntitlementsRequest struct {
	// Customer ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetCustomerEntitlementsRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetCustomerEntitlementsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	DtoCustomerEntitlementsResponse *components.DtoCustomerEntitlementsResponse
}

func (g GetCustomerEntitlementsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetCustomerEntitlementsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetCustomerEntitlementsResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetCustomerEntitlementsResponse) GetDtoCustomerEntitlementsResponse() *components.DtoCustomerEntitlementsResponse {
	if g == nil {
		return nil
	}
	return g.DtoCustomerEntitlementsResponse
}
