// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flexprice/flexprice-go/internal/utils"
	"github.com/flexprice/flexprice-go/models/components"
)

type GetCustomerUsageSummaryRequest struct {
	CustomerID        *string  `queryParam:"style=form,explode=true,name=customer_id"`
	CustomerLookupKey *string  `queryParam:"style=form,explode=true,name=customer_lookup_key"`
	FeatureIds        []string `queryParam:"style=form,explode=false,name=feature_ids"`
	FeatureLookupKeys []string `queryParam:"style=form,explode=false,name=feature_lookup_keys"`
	SubscriptionIds   []string `queryParam:"style=form,explode=false,name=subscription_ids"`
}

func (g GetCustomerUsageSummaryRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetCustomerUsageSummaryRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetCustomerUsageSummaryRequest) GetCustomerID() *string {
	if g == nil {
		return nil
	}
	return g.CustomerID
}

func (g *GetCustomerUsageSummaryRequest) GetCustomerLookupKey() *string {
	if g == nil {
		return nil
	}
	return g.CustomerLookupKey
}

func (g *GetCustomerUsageSummaryRequest) GetFeatureIds() []string {
	if g == nil {
		return nil
	}
	return g.FeatureIds
}

func (g *GetCustomerUsageSummaryRequest) GetFeatureLookupKeys() []string {
	if g == nil {
		return nil
	}
	return g.FeatureLookupKeys
}

func (g *GetCustomerUsageSummaryRequest) GetSubscriptionIds() []string {
	if g == nil {
		return nil
	}
	return g.SubscriptionIds
}

type GetCustomerUsageSummaryResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	DtoCustomerUsageSummaryResponse *components.DtoCustomerUsageSummaryResponse
}

func (g GetCustomerUsageSummaryResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetCustomerUsageSummaryResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetCustomerUsageSummaryResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetCustomerUsageSummaryResponse) GetDtoCustomerUsageSummaryResponse() *components.DtoCustomerUsageSummaryResponse {
	if g == nil {
		return nil
	}
	return g.DtoCustomerUsageSummaryResponse
}
