// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flexprice/flexprice-go/internal/utils"
	"github.com/flexprice/flexprice-go/models/components"
)

type GetGroupRequest struct {
	// Group ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetGroupRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetGroupResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	DtoGroupResponse *components.DtoGroupResponse
}

func (g GetGroupResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetGroupResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetGroupResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetGroupResponse) GetDtoGroupResponse() *components.DtoGroupResponse {
	if g == nil {
		return nil
	}
	return g.DtoGroupResponse
}
