// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flexprice/flexprice-go/internal/utils"
	"github.com/flexprice/flexprice-go/models/components"
)

type GetInvoiceRequest struct {
	// Invoice ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Include source-level price breakdown for usage line items (legacy)
	ExpandBySource *bool `queryParam:"style=form,explode=true,name=expand_by_source"`
	// Group usage breakdown by specified fields (e.g., source, feature_id, properties.org_id)
	GroupBy []string `queryParam:"style=form,explode=false,name=group_by"`
}

func (g GetInvoiceRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetInvoiceRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetInvoiceRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetInvoiceRequest) GetExpandBySource() *bool {
	if g == nil {
		return nil
	}
	return g.ExpandBySource
}

func (g *GetInvoiceRequest) GetGroupBy() []string {
	if g == nil {
		return nil
	}
	return g.GroupBy
}

type GetInvoiceResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	DtoInvoiceResponse *components.DtoInvoiceResponse
}

func (g GetInvoiceResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetInvoiceResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetInvoiceResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetInvoiceResponse) GetDtoInvoiceResponse() *components.DtoInvoiceResponse {
	if g == nil {
		return nil
	}
	return g.DtoInvoiceResponse
}
