// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flexprice/flexprice-go/internal/utils"
	"github.com/flexprice/flexprice-go/models/components"
)

type GetUsageByMeterResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	DtoGetUsageResponse *components.DtoGetUsageResponse
}

func (g GetUsageByMeterResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetUsageByMeterResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetUsageByMeterResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetUsageByMeterResponse) GetDtoGetUsageResponse() *components.DtoGetUsageResponse {
	if g == nil {
		return nil
	}
	return g.DtoGetUsageResponse
}
