// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flexprice/flexprice-go/internal/utils"
	"github.com/flexprice/flexprice-go/models/components"
)

type GetUsageAnalyticsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	DtoGetUsageAnalyticsResponse *components.DtoGetUsageAnalyticsResponse
}

func (g GetUsageAnalyticsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetUsageAnalyticsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetUsageAnalyticsResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetUsageAnalyticsResponse) GetDtoGetUsageAnalyticsResponse() *components.DtoGetUsageAnalyticsResponse {
	if g == nil {
		return nil
	}
	return g.DtoGetUsageAnalyticsResponse
}
