// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetV1SubscriptionsSubscriptionIDSchedulesRequest struct {
	// Subscription ID
	SubscriptionID string `pathParam:"style=simple,explode=false,name=subscription_id"`
}

func (g *GetV1SubscriptionsSubscriptionIDSchedulesRequest) GetSubscriptionID() string {
	if g == nil {
		return ""
	}
	return g.SubscriptionID
}
