// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetV1SubscriptionSchedulesRequest struct {
	// Filter to pending schedules only
	PendingOnly *bool `queryParam:"style=form,explode=true,name=pending_only"`
	// Filter by subscription ID
	SubscriptionID *string `queryParam:"style=form,explode=true,name=subscription_id"`
	// Limit results
	Limit *int64 `queryParam:"style=form,explode=true,name=limit"`
	// Offset for pagination
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

func (g *GetV1SubscriptionSchedulesRequest) GetPendingOnly() *bool {
	if g == nil {
		return nil
	}
	return g.PendingOnly
}

func (g *GetV1SubscriptionSchedulesRequest) GetSubscriptionID() *string {
	if g == nil {
		return nil
	}
	return g.SubscriptionID
}

func (g *GetV1SubscriptionSchedulesRequest) GetLimit() *int64 {
	if g == nil {
		return nil
	}
	return g.Limit
}

func (g *GetV1SubscriptionSchedulesRequest) GetOffset() *int64 {
	if g == nil {
		return nil
	}
	return g.Offset
}
