// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flexprice/flexprice-go/internal/utils"
	"github.com/flexprice/flexprice-go/models/components"
)

type GetWalletsByCustomerIDRequest struct {
	// Customer ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetWalletsByCustomerIDRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetWalletsByCustomerIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	DtoWalletResponses []components.DtoWalletResponse
}

func (g GetWalletsByCustomerIDResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetWalletsByCustomerIDResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetWalletsByCustomerIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetWalletsByCustomerIDResponse) GetDtoWalletResponses() []components.DtoWalletResponse {
	if g == nil {
		return nil
	}
	return g.DtoWalletResponses
}
