// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flexprice/flexprice-go/internal/utils"
	"github.com/flexprice/flexprice-go/models/components"
)

type HandleQuickbooksWebhookRequest struct {
	// Tenant ID
	TenantID string `pathParam:"style=simple,explode=false,name=tenant_id"`
	// Environment ID
	EnvironmentID string `pathParam:"style=simple,explode=false,name=environment_id"`
	// QuickBooks webhook signature
	IntuitSignature *string `header:"style=simple,explode=false,name=intuit-signature"`
}

func (h *HandleQuickbooksWebhookRequest) GetTenantID() string {
	if h == nil {
		return ""
	}
	return h.TenantID
}

func (h *HandleQuickbooksWebhookRequest) GetEnvironmentID() string {
	if h == nil {
		return ""
	}
	return h.EnvironmentID
}

func (h *HandleQuickbooksWebhookRequest) GetIntuitSignature() *string {
	if h == nil {
		return nil
	}
	return h.IntuitSignature
}

type HandleQuickbooksWebhookResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Webhook processed successfully
	Object map[string]any
}

func (h HandleQuickbooksWebhookResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(h, "", false)
}

func (h *HandleQuickbooksWebhookResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &h, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (h *HandleQuickbooksWebhookResponse) GetHTTPMeta() components.HTTPMetadata {
	if h == nil {
		return components.HTTPMetadata{}
	}
	return h.HTTPMeta
}

func (h *HandleQuickbooksWebhookResponse) GetObject() map[string]any {
	if h == nil {
		return nil
	}
	return h.Object
}
