// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flexprice/flexprice-go/internal/utils"
	"github.com/flexprice/flexprice-go/models/components"
)

type HandleMoyasarWebhookRequest struct {
	// Tenant ID
	TenantID string `pathParam:"style=simple,explode=false,name=tenant_id"`
	// Environment ID
	EnvironmentID string `pathParam:"style=simple,explode=false,name=environment_id"`
	// Moyasar webhook signature
	XMoyasarSignature *string `header:"style=simple,explode=false,name=X-Moyasar-Signature"`
}

func (h *HandleMoyasarWebhookRequest) GetTenantID() string {
	if h == nil {
		return ""
	}
	return h.TenantID
}

func (h *HandleMoyasarWebhookRequest) GetEnvironmentID() string {
	if h == nil {
		return ""
	}
	return h.EnvironmentID
}

func (h *HandleMoyasarWebhookRequest) GetXMoyasarSignature() *string {
	if h == nil {
		return nil
	}
	return h.XMoyasarSignature
}

type HandleMoyasarWebhookResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Webhook received (always returns 200)
	Object map[string]any
}

func (h HandleMoyasarWebhookResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(h, "", false)
}

func (h *HandleMoyasarWebhookResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &h, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (h *HandleMoyasarWebhookResponse) GetHTTPMeta() components.HTTPMetadata {
	if h == nil {
		return components.HTTPMetadata{}
	}
	return h.HTTPMeta
}

func (h *HandleMoyasarWebhookResponse) GetObject() map[string]any {
	if h == nil {
		return nil
	}
	return h.Object
}
