// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flexprice/flexprice-go/internal/utils"
	"github.com/flexprice/flexprice-go/models/components"
)

type HandleNomodWebhookRequest struct {
	// Tenant ID
	TenantID string `pathParam:"style=simple,explode=false,name=tenant_id"`
	// Environment ID
	EnvironmentID string `pathParam:"style=simple,explode=false,name=environment_id"`
	// Nomod webhook secret (if configured)
	XAPIKey *string `header:"style=simple,explode=false,name=X-API-KEY"`
}

func (h *HandleNomodWebhookRequest) GetTenantID() string {
	if h == nil {
		return ""
	}
	return h.TenantID
}

func (h *HandleNomodWebhookRequest) GetEnvironmentID() string {
	if h == nil {
		return ""
	}
	return h.EnvironmentID
}

func (h *HandleNomodWebhookRequest) GetXAPIKey() *string {
	if h == nil {
		return nil
	}
	return h.XAPIKey
}

type HandleNomodWebhookResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Webhook processed successfully
	Object map[string]any
}

func (h HandleNomodWebhookResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(h, "", false)
}

func (h *HandleNomodWebhookResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &h, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (h *HandleNomodWebhookResponse) GetHTTPMeta() components.HTTPMetadata {
	if h == nil {
		return components.HTTPMetadata{}
	}
	return h.HTTPMeta
}

func (h *HandleNomodWebhookResponse) GetObject() map[string]any {
	if h == nil {
		return nil
	}
	return h.Object
}
