// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flexprice/flexprice-go/internal/utils"
	"github.com/flexprice/flexprice-go/models/components"
)

type ListAllSubscriptionSchedulesRequest struct {
	// Filter to pending schedules only
	PendingOnly *bool `queryParam:"style=form,explode=true,name=pending_only"`
	// Filter by subscription ID
	SubscriptionID *string `queryParam:"style=form,explode=true,name=subscription_id"`
	// Limit results
	Limit *int64 `queryParam:"style=form,explode=true,name=limit"`
	// Offset for pagination
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

func (l *ListAllSubscriptionSchedulesRequest) GetPendingOnly() *bool {
	if l == nil {
		return nil
	}
	return l.PendingOnly
}

func (l *ListAllSubscriptionSchedulesRequest) GetSubscriptionID() *string {
	if l == nil {
		return nil
	}
	return l.SubscriptionID
}

func (l *ListAllSubscriptionSchedulesRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListAllSubscriptionSchedulesRequest) GetOffset() *int64 {
	if l == nil {
		return nil
	}
	return l.Offset
}

type ListAllSubscriptionSchedulesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	DtoGetPendingSchedulesResponse *components.DtoGetPendingSchedulesResponse
}

func (l ListAllSubscriptionSchedulesResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListAllSubscriptionSchedulesResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListAllSubscriptionSchedulesResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListAllSubscriptionSchedulesResponse) GetDtoGetPendingSchedulesResponse() *components.DtoGetPendingSchedulesResponse {
	if l == nil {
		return nil
	}
	return l.DtoGetPendingSchedulesResponse
}
