// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flexprice/flexprice-go/internal/utils"
	"github.com/flexprice/flexprice-go/models/components"
)

type ProcessCreditNoteRequest struct {
	// Credit note ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (p *ProcessCreditNoteRequest) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

type ProcessCreditNoteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	DtoCreditNoteResponse *components.DtoCreditNoteResponse
}

func (p ProcessCreditNoteResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *ProcessCreditNoteResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *ProcessCreditNoteResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *ProcessCreditNoteResponse) GetDtoCreditNoteResponse() *components.DtoCreditNoteResponse {
	if p == nil {
		return nil
	}
	return p.DtoCreditNoteResponse
}
