// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flexprice/flexprice-go/internal/utils"
	"github.com/flexprice/flexprice-go/models/components"
)

type QuerySubscriptionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	DtoListSubscriptionsResponse *components.DtoListSubscriptionsResponse
}

func (q QuerySubscriptionResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(q, "", false)
}

func (q *QuerySubscriptionResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &q, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (q *QuerySubscriptionResponse) GetHTTPMeta() components.HTTPMetadata {
	if q == nil {
		return components.HTTPMetadata{}
	}
	return q.HTTPMeta
}

func (q *QuerySubscriptionResponse) GetDtoListSubscriptionsResponse() *components.DtoListSubscriptionsResponse {
	if q == nil {
		return nil
	}
	return q.DtoListSubscriptionsResponse
}
