// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flexprice/flexprice-go/internal/utils"
	"github.com/flexprice/flexprice-go/models/components"
)

type QueryCouponResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	DtoListCouponsResponse *components.DtoListCouponsResponse
}

func (q QueryCouponResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(q, "", false)
}

func (q *QueryCouponResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &q, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (q *QueryCouponResponse) GetHTTPMeta() components.HTTPMetadata {
	if q == nil {
		return components.HTTPMetadata{}
	}
	return q.HTTPMeta
}

func (q *QueryCouponResponse) GetDtoListCouponsResponse() *components.DtoListCouponsResponse {
	if q == nil {
		return nil
	}
	return q.DtoListCouponsResponse
}
