// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flexprice/flexprice-go/internal/utils"
	"github.com/flexprice/flexprice-go/models/components"
)

type QueryUserResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	DtoListUsersResponse *components.DtoListUsersResponse
}

func (q QueryUserResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(q, "", false)
}

func (q *QueryUserResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &q, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (q *QueryUserResponse) GetHTTPMeta() components.HTTPMetadata {
	if q == nil {
		return components.HTTPMetadata{}
	}
	return q.HTTPMeta
}

func (q *QueryUserResponse) GetDtoListUsersResponse() *components.DtoListUsersResponse {
	if q == nil {
		return nil
	}
	return q.DtoListUsersResponse
}
