// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flexprice/flexprice-go/internal/utils"
	"github.com/flexprice/flexprice-go/models/components"
)

type QueryWalletResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	ListResponseDtoWalletResponse *components.ListResponseDtoWalletResponse
}

func (q QueryWalletResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(q, "", false)
}

func (q *QueryWalletResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &q, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (q *QueryWalletResponse) GetHTTPMeta() components.HTTPMetadata {
	if q == nil {
		return components.HTTPMetadata{}
	}
	return q.HTTPMeta
}

func (q *QueryWalletResponse) GetListResponseDtoWalletResponse() *components.ListResponseDtoWalletResponse {
	if q == nil {
		return nil
	}
	return q.ListResponseDtoWalletResponse
}
