// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flexprice/flexprice-go/internal/utils"
	"github.com/flexprice/flexprice-go/models/components"
)

type QueryEntitlementResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	DtoListEntitlementsResponse *components.DtoListEntitlementsResponse
}

func (q QueryEntitlementResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(q, "", false)
}

func (q *QueryEntitlementResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &q, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (q *QueryEntitlementResponse) GetHTTPMeta() components.HTTPMetadata {
	if q == nil {
		return components.HTTPMetadata{}
	}
	return q.HTTPMeta
}

func (q *QueryEntitlementResponse) GetDtoListEntitlementsResponse() *components.DtoListEntitlementsResponse {
	if q == nil {
		return nil
	}
	return q.DtoListEntitlementsResponse
}
