// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flexprice/flexprice-go/internal/utils"
	"github.com/flexprice/flexprice-go/models/components"
)

type QueryPriceUnitResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	DtoListPriceUnitsResponse *components.DtoListPriceUnitsResponse
}

func (q QueryPriceUnitResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(q, "", false)
}

func (q *QueryPriceUnitResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &q, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (q *QueryPriceUnitResponse) GetHTTPMeta() components.HTTPMetadata {
	if q == nil {
		return components.HTTPMetadata{}
	}
	return q.HTTPMeta
}

func (q *QueryPriceUnitResponse) GetDtoListPriceUnitsResponse() *components.DtoListPriceUnitsResponse {
	if q == nil {
		return nil
	}
	return q.DtoListPriceUnitsResponse
}
