// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flexprice/flexprice-go/internal/utils"
	"github.com/flexprice/flexprice-go/models/components"
)

type RemoveSubscriptionAddonResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	DtoSuccessResponse *components.DtoSuccessResponse
}

func (r RemoveSubscriptionAddonResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RemoveSubscriptionAddonResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RemoveSubscriptionAddonResponse) GetHTTPMeta() components.HTTPMetadata {
	if r == nil {
		return components.HTTPMetadata{}
	}
	return r.HTTPMeta
}

func (r *RemoveSubscriptionAddonResponse) GetDtoSuccessResponse() *components.DtoSuccessResponse {
	if r == nil {
		return nil
	}
	return r.DtoSuccessResponse
}
