// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flexprice/flexprice-go/internal/utils"
	"github.com/flexprice/flexprice-go/models/components"
)

// ScheduleUpdateBillingPeriodRequest - Schedule Update Billing Period Request
type ScheduleUpdateBillingPeriodRequest struct {
}

// ScheduleUpdateBillingPeriodResponseBody - OK
type ScheduleUpdateBillingPeriodResponseBody struct {
}

type ScheduleUpdateBillingPeriodResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	Object *ScheduleUpdateBillingPeriodResponseBody
}

func (s ScheduleUpdateBillingPeriodResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *ScheduleUpdateBillingPeriodResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *ScheduleUpdateBillingPeriodResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *ScheduleUpdateBillingPeriodResponse) GetObject() *ScheduleUpdateBillingPeriodResponseBody {
	if s == nil {
		return nil
	}
	return s.Object
}
