// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flexprice/flexprice-go/internal/utils"
	"github.com/flexprice/flexprice-go/models/components"
)

type UpdateCouponRequest struct {
	// Coupon ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Coupon update request
	Body components.DtoUpdateCouponRequest `request:"mediaType=application/json"`
}

func (u *UpdateCouponRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateCouponRequest) GetBody() components.DtoUpdateCouponRequest {
	if u == nil {
		return components.DtoUpdateCouponRequest{}
	}
	return u.Body
}

type UpdateCouponResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	DtoCouponResponse *components.DtoCouponResponse
}

func (u UpdateCouponResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateCouponResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateCouponResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateCouponResponse) GetDtoCouponResponse() *components.DtoCouponResponse {
	if u == nil {
		return nil
	}
	return u.DtoCouponResponse
}
