// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flexprice/flexprice-go/internal/utils"
	"github.com/flexprice/flexprice-go/models/components"
)

type UpdatePriceUnitRequest struct {
	// Price unit ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Price unit details to update
	Body components.DtoUpdatePriceUnitRequest `request:"mediaType=application/json"`
}

func (u *UpdatePriceUnitRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdatePriceUnitRequest) GetBody() components.DtoUpdatePriceUnitRequest {
	if u == nil {
		return components.DtoUpdatePriceUnitRequest{}
	}
	return u.Body
}

type UpdatePriceUnitResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	DtoPriceUnitResponse *components.DtoPriceUnitResponse
}

func (u UpdatePriceUnitResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdatePriceUnitResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdatePriceUnitResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdatePriceUnitResponse) GetDtoPriceUnitResponse() *components.DtoPriceUnitResponse {
	if u == nil {
		return nil
	}
	return u.DtoPriceUnitResponse
}
