// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flexprice/flexprice-go/internal/utils"
	"github.com/flexprice/flexprice-go/models/components"
)

type UpdateSubscriptionRequest struct {
	// Subscription ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Update Subscription Request
	Body components.DtoUpdateSubscriptionRequest `request:"mediaType=application/json"`
}

func (u *UpdateSubscriptionRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateSubscriptionRequest) GetBody() components.DtoUpdateSubscriptionRequest {
	if u == nil {
		return components.DtoUpdateSubscriptionRequest{}
	}
	return u.Body
}

type UpdateSubscriptionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	DtoSubscriptionResponse *components.DtoSubscriptionResponse
}

func (u UpdateSubscriptionResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateSubscriptionResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateSubscriptionResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateSubscriptionResponse) GetDtoSubscriptionResponse() *components.DtoSubscriptionResponse {
	if u == nil {
		return nil
	}
	return u.DtoSubscriptionResponse
}
