// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flexprice/flexprice-go/internal/utils"
	"github.com/flexprice/flexprice-go/models/components"
)

type UpdateEntitlementRequest struct {
	// Entitlement ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Entitlement configuration
	Body components.DtoUpdateEntitlementRequest `request:"mediaType=application/json"`
}

func (u *UpdateEntitlementRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateEntitlementRequest) GetBody() components.DtoUpdateEntitlementRequest {
	if u == nil {
		return components.DtoUpdateEntitlementRequest{}
	}
	return u.Body
}

type UpdateEntitlementResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	DtoEntitlementResponse *components.DtoEntitlementResponse
}

func (u UpdateEntitlementResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateEntitlementResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateEntitlementResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateEntitlementResponse) GetDtoEntitlementResponse() *components.DtoEntitlementResponse {
	if u == nil {
		return nil
	}
	return u.DtoEntitlementResponse
}
