// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flexprice/flexprice-go/internal/utils"
	"github.com/flexprice/flexprice-go/models/components"
)

type UpdatePlanRequest struct {
	// Plan ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Plan update
	Body components.DtoUpdatePlanRequest `request:"mediaType=application/json"`
}

func (u *UpdatePlanRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdatePlanRequest) GetBody() components.DtoUpdatePlanRequest {
	if u == nil {
		return components.DtoUpdatePlanRequest{}
	}
	return u.Body
}

type UpdatePlanResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	DtoPlanResponse *components.DtoPlanResponse
}

func (u UpdatePlanResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdatePlanResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdatePlanResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdatePlanResponse) GetDtoPlanResponse() *components.DtoPlanResponse {
	if u == nil {
		return nil
	}
	return u.DtoPlanResponse
}
