// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flexprice/flexprice-go/internal/utils"
	"github.com/flexprice/flexprice-go/models/components"
)

type UpdateTaxAssociationRequest struct {
	// Tax Config ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Tax Config Request
	Body components.DtoTaxAssociationUpdateRequest `request:"mediaType=application/json"`
}

func (u *UpdateTaxAssociationRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateTaxAssociationRequest) GetBody() components.DtoTaxAssociationUpdateRequest {
	if u == nil {
		return components.DtoTaxAssociationUpdateRequest{}
	}
	return u.Body
}

type UpdateTaxAssociationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	DtoTaxAssociationResponse *components.DtoTaxAssociationResponse
}

func (u UpdateTaxAssociationResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateTaxAssociationResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateTaxAssociationResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateTaxAssociationResponse) GetDtoTaxAssociationResponse() *components.DtoTaxAssociationResponse {
	if u == nil {
		return nil
	}
	return u.DtoTaxAssociationResponse
}
