// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flexprice/flexprice-go/internal/utils"
	"github.com/flexprice/flexprice-go/models/components"
)

type UpdateCustomerRequest struct {
	// Customer ID
	ID *string `queryParam:"style=form,explode=true,name=id"`
	// Customer External ID
	ExternalCustomerID *string `queryParam:"style=form,explode=true,name=external_customer_id"`
	// Customer
	Body components.DtoUpdateCustomerRequest `request:"mediaType=application/json"`
}

func (u *UpdateCustomerRequest) GetID() *string {
	if u == nil {
		return nil
	}
	return u.ID
}

func (u *UpdateCustomerRequest) GetExternalCustomerID() *string {
	if u == nil {
		return nil
	}
	return u.ExternalCustomerID
}

func (u *UpdateCustomerRequest) GetBody() components.DtoUpdateCustomerRequest {
	if u == nil {
		return components.DtoUpdateCustomerRequest{}
	}
	return u.Body
}

type UpdateCustomerResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	DtoCustomerResponse *components.DtoCustomerResponse
}

func (u UpdateCustomerResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateCustomerResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateCustomerResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateCustomerResponse) GetDtoCustomerResponse() *components.DtoCustomerResponse {
	if u == nil {
		return nil
	}
	return u.DtoCustomerResponse
}
