// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flexprice/flexprice-go/internal/utils"
	"github.com/flexprice/flexprice-go/models/components"
)

type VoidCreditNoteRequest struct {
	// Credit note ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (v *VoidCreditNoteRequest) GetID() string {
	if v == nil {
		return ""
	}
	return v.ID
}

type VoidCreditNoteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	DtoCreditNoteResponse *components.DtoCreditNoteResponse
}

func (v VoidCreditNoteResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *VoidCreditNoteResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *VoidCreditNoteResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *VoidCreditNoteResponse) GetDtoCreditNoteResponse() *components.DtoCreditNoteResponse {
	if v == nil {
		return nil
	}
	return v.DtoCreditNoteResponse
}
