// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AlertThreshold struct {
	Condition *AlertCondition `json:"condition,omitzero"`
	Threshold *float64        `json:"threshold,omitzero"`
}

func (a *AlertThreshold) GetCondition() *AlertCondition {
	if a == nil {
		return nil
	}
	return a.Condition
}

func (a *AlertThreshold) GetThreshold() *float64 {
	if a == nil {
		return nil
	}
	return a.Threshold
}
