// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CancellationType string

const (
	CancellationTypeImmediate   CancellationType = "immediate"
	CancellationTypeEndOfPeriod CancellationType = "end_of_period"
)

func (e CancellationType) ToPointer() *CancellationType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *CancellationType) IsExact() bool {
	if e != nil {
		switch *e {
		case "immediate", "end_of_period":
			return true
		}
	}
	return false
}
