// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DtoCreateUserRequest struct {
	// Roles are required
	Roles []string `json:"roles"`
	Type  UserType `json:"type"`
}

func (d *DtoCreateUserRequest) GetRoles() []string {
	if d == nil {
		return []string{}
	}
	return d.Roles
}

func (d *DtoCreateUserRequest) GetType() UserType {
	if d == nil {
		return UserType("")
	}
	return d.Type
}
