// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/flexprice/flexprice-go/internal/utils"
)

type DtoCreateCreditGrantRequest struct {
	Cadence TypesCreditGrantCadence `json:"cadence"`
	// amount in the currency =  number of credits * conversion_rate
	// ex if conversion_rate is 1, then 1 USD = 1 credit
	// ex if conversion_rate is 2, then 1 USD = 0.5 credits
	// ex if conversion_rate is 0.5, then 1 USD = 2 credits
	ConversionRate         *string                             `json:"conversion_rate,omitzero"`
	Credits                string                              `json:"credits"`
	EndDate                *string                             `json:"end_date,omitzero"`
	ExpirationDuration     *int64                              `json:"expiration_duration,omitzero"`
	ExpirationDurationUnit *TypesCreditGrantExpiryDurationUnit `json:"expiration_duration_unit,omitzero"`
	ExpirationType         *TypesCreditGrantExpiryType         `json:"expiration_type,omitzero"`
	Metadata               map[string]string                   `json:"metadata,omitzero"`
	Name                   string                              `json:"name"`
	Period                 *TypesCreditGrantPeriod             `json:"period,omitzero"`
	PeriodCount            *int64                              `json:"period_count,omitzero"`
	PlanID                 *string                             `json:"plan_id,omitzero"`
	Priority               *int64                              `json:"priority,omitzero"`
	Scope                  TypesCreditGrantScope               `json:"scope"`
	StartDate              *string                             `json:"start_date,omitzero"`
	SubscriptionID         *string                             `json:"subscription_id,omitzero"`
	// topup_conversion_rate is the conversion rate for the topup to the currency
	// ex if topup_conversion_rate is 1, then 1 USD = 1 credit
	// ex if topup_conversion_rate is 2, then 1 USD = 0.5 credits
	// ex if topup_conversion_rate is 0.5, then 1 USD = 2 credits
	TopupConversionRate *string `json:"topup_conversion_rate,omitzero"`
}

func (d DtoCreateCreditGrantRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DtoCreateCreditGrantRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DtoCreateCreditGrantRequest) GetCadence() TypesCreditGrantCadence {
	if d == nil {
		return TypesCreditGrantCadence("")
	}
	return d.Cadence
}

func (d *DtoCreateCreditGrantRequest) GetConversionRate() *string {
	if d == nil {
		return nil
	}
	return d.ConversionRate
}

func (d *DtoCreateCreditGrantRequest) GetCredits() string {
	if d == nil {
		return ""
	}
	return d.Credits
}

func (d *DtoCreateCreditGrantRequest) GetEndDate() *string {
	if d == nil {
		return nil
	}
	return d.EndDate
}

func (d *DtoCreateCreditGrantRequest) GetExpirationDuration() *int64 {
	if d == nil {
		return nil
	}
	return d.ExpirationDuration
}

func (d *DtoCreateCreditGrantRequest) GetExpirationDurationUnit() *TypesCreditGrantExpiryDurationUnit {
	if d == nil {
		return nil
	}
	return d.ExpirationDurationUnit
}

func (d *DtoCreateCreditGrantRequest) GetExpirationType() *TypesCreditGrantExpiryType {
	if d == nil {
		return nil
	}
	return d.ExpirationType
}

func (d *DtoCreateCreditGrantRequest) GetMetadata() map[string]string {
	if d == nil {
		return nil
	}
	return d.Metadata
}

func (d *DtoCreateCreditGrantRequest) GetName() string {
	if d == nil {
		return ""
	}
	return d.Name
}

func (d *DtoCreateCreditGrantRequest) GetPeriod() *TypesCreditGrantPeriod {
	if d == nil {
		return nil
	}
	return d.Period
}

func (d *DtoCreateCreditGrantRequest) GetPeriodCount() *int64 {
	if d == nil {
		return nil
	}
	return d.PeriodCount
}

func (d *DtoCreateCreditGrantRequest) GetPlanID() *string {
	if d == nil {
		return nil
	}
	return d.PlanID
}

func (d *DtoCreateCreditGrantRequest) GetPriority() *int64 {
	if d == nil {
		return nil
	}
	return d.Priority
}

func (d *DtoCreateCreditGrantRequest) GetScope() TypesCreditGrantScope {
	if d == nil {
		return TypesCreditGrantScope("")
	}
	return d.Scope
}

func (d *DtoCreateCreditGrantRequest) GetStartDate() *string {
	if d == nil {
		return nil
	}
	return d.StartDate
}

func (d *DtoCreateCreditGrantRequest) GetSubscriptionID() *string {
	if d == nil {
		return nil
	}
	return d.SubscriptionID
}

func (d *DtoCreateCreditGrantRequest) GetTopupConversionRate() *string {
	if d == nil {
		return nil
	}
	return d.TopupConversionRate
}
