// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// DtoCancelScheduleRequest - Request to cancel a subscription schedule (supports two modes)
type DtoCancelScheduleRequest struct {
	// schedule_id is the ID of the schedule to cancel (optional if subscription_id and schedule_type are provided)
	ScheduleID   *string                              `json:"schedule_id,omitzero"`
	ScheduleType *TypesSubscriptionScheduleChangeType `json:"schedule_type,omitzero"`
	// subscription_id is the ID of the subscription (required if schedule_id is not provided)
	SubscriptionID *string `json:"subscription_id,omitzero"`
}

func (d *DtoCancelScheduleRequest) GetScheduleID() *string {
	if d == nil {
		return nil
	}
	return d.ScheduleID
}

func (d *DtoCancelScheduleRequest) GetScheduleType() *TypesSubscriptionScheduleChangeType {
	if d == nil {
		return nil
	}
	return d.ScheduleType
}

func (d *DtoCancelScheduleRequest) GetSubscriptionID() *string {
	if d == nil {
		return nil
	}
	return d.SubscriptionID
}
