// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/flexprice/flexprice-go/internal/utils"
)

type DtoCreateTaxAssociationRequest struct {
	AutoApply          *bool              `json:"auto_apply,omitzero"`
	Currency           *string            `json:"currency,omitzero"`
	EntityID           *string            `json:"entity_id,omitzero"`
	EntityType         *TaxRateEntityType `json:"entity_type,omitzero"`
	ExternalCustomerID *string            `json:"external_customer_id,omitzero"`
	Metadata           map[string]string  `json:"metadata,omitzero"`
	Priority           *int64             `json:"priority,omitzero"`
	TaxRateCode        string             `json:"tax_rate_code"`
}

func (d DtoCreateTaxAssociationRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DtoCreateTaxAssociationRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DtoCreateTaxAssociationRequest) GetAutoApply() *bool {
	if d == nil {
		return nil
	}
	return d.AutoApply
}

func (d *DtoCreateTaxAssociationRequest) GetCurrency() *string {
	if d == nil {
		return nil
	}
	return d.Currency
}

func (d *DtoCreateTaxAssociationRequest) GetEntityID() *string {
	if d == nil {
		return nil
	}
	return d.EntityID
}

func (d *DtoCreateTaxAssociationRequest) GetEntityType() *TaxRateEntityType {
	if d == nil {
		return nil
	}
	return d.EntityType
}

func (d *DtoCreateTaxAssociationRequest) GetExternalCustomerID() *string {
	if d == nil {
		return nil
	}
	return d.ExternalCustomerID
}

func (d *DtoCreateTaxAssociationRequest) GetMetadata() map[string]string {
	if d == nil {
		return nil
	}
	return d.Metadata
}

func (d *DtoCreateTaxAssociationRequest) GetPriority() *int64 {
	if d == nil {
		return nil
	}
	return d.Priority
}

func (d *DtoCreateTaxAssociationRequest) GetTaxRateCode() string {
	if d == nil {
		return ""
	}
	return d.TaxRateCode
}
