// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// DtoCancelScheduleResponse - Confirmation of schedule cancellation
type DtoCancelScheduleResponse struct {
	// message is a confirmation message
	Message *string              `json:"message,omitzero"`
	Status  *TypesScheduleStatus `json:"status,omitzero"`
}

func (d *DtoCancelScheduleResponse) GetMessage() *string {
	if d == nil {
		return nil
	}
	return d.Message
}

func (d *DtoCancelScheduleResponse) GetStatus() *TypesScheduleStatus {
	if d == nil {
		return nil
	}
	return d.Status
}
