// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DtoCustomAnalyticItem struct {
	// Name of the feature this applies to
	FeatureName *string `json:"feature_name,omitzero"`
	ID          *string `json:"id,omitzero"`
	// Calculation name (e.g., "Revenue per Minute")
	Name *string `json:"name,omitzero"`
	// "feature", "meter", "event_name"
	Type  *string `json:"type,omitzero"`
	Value *string `json:"value,omitzero"`
}

func (d *DtoCustomAnalyticItem) GetFeatureName() *string {
	if d == nil {
		return nil
	}
	return d.FeatureName
}

func (d *DtoCustomAnalyticItem) GetID() *string {
	if d == nil {
		return nil
	}
	return d.ID
}

func (d *DtoCustomAnalyticItem) GetName() *string {
	if d == nil {
		return nil
	}
	return d.Name
}

func (d *DtoCustomAnalyticItem) GetType() *string {
	if d == nil {
		return nil
	}
	return d.Type
}

func (d *DtoCustomAnalyticItem) GetValue() *string {
	if d == nil {
		return nil
	}
	return d.Value
}
