// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/flexprice/flexprice-go/internal/utils"
)

type DtoDebugTracker struct {
	CustomerLookup             *DtoCustomerLookupResult             `json:"customer_lookup,omitzero"`
	FailurePoint               *TypesFailurePoint                   `json:"failure_point,omitzero"`
	MeterMatching              *DtoMeterMatchingResult              `json:"meter_matching,omitzero"`
	PriceLookup                *DtoPriceLookupResult                `json:"price_lookup,omitzero"`
	SubscriptionLineItemLookup *DtoSubscriptionLineItemLookupResult `json:"subscription_line_item_lookup,omitzero"`
}

func (d DtoDebugTracker) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DtoDebugTracker) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DtoDebugTracker) GetCustomerLookup() *DtoCustomerLookupResult {
	if d == nil {
		return nil
	}
	return d.CustomerLookup
}

func (d *DtoDebugTracker) GetFailurePoint() *TypesFailurePoint {
	if d == nil {
		return nil
	}
	return d.FailurePoint
}

func (d *DtoDebugTracker) GetMeterMatching() *DtoMeterMatchingResult {
	if d == nil {
		return nil
	}
	return d.MeterMatching
}

func (d *DtoDebugTracker) GetPriceLookup() *DtoPriceLookupResult {
	if d == nil {
		return nil
	}
	return d.PriceLookup
}

func (d *DtoDebugTracker) GetSubscriptionLineItemLookup() *DtoSubscriptionLineItemLookupResult {
	if d == nil {
		return nil
	}
	return d.SubscriptionLineItemLookup
}
