// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/flexprice/flexprice-go/internal/utils"
)

type DtoGetUsageAnalyticsRequest struct {
	EndTime *string `json:"end_time,omitzero"`
	// allowed values: "price", "meter", "feature", "subscription_line_item","plan","addon"
	Expand             []string `json:"expand,omitzero"`
	ExternalCustomerID string   `json:"external_customer_id"`
	FeatureIds         []string `json:"feature_ids,omitzero"`
	// allowed values: "source", "feature_id", "properties.<field_name>"
	GroupBy []string `json:"group_by,omitzero"`
	// Property filters to filter the events by the keys in `properties` field of the event
	PropertyFilters map[string][]string `json:"property_filters,omitzero"`
	Sources         []string            `json:"sources,omitzero"`
	StartTime       *string             `json:"start_time,omitzero"`
	WindowSize      *TypesWindowSize    `json:"window_size,omitzero"`
}

func (d DtoGetUsageAnalyticsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DtoGetUsageAnalyticsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DtoGetUsageAnalyticsRequest) GetEndTime() *string {
	if d == nil {
		return nil
	}
	return d.EndTime
}

func (d *DtoGetUsageAnalyticsRequest) GetExpand() []string {
	if d == nil {
		return nil
	}
	return d.Expand
}

func (d *DtoGetUsageAnalyticsRequest) GetExternalCustomerID() string {
	if d == nil {
		return ""
	}
	return d.ExternalCustomerID
}

func (d *DtoGetUsageAnalyticsRequest) GetFeatureIds() []string {
	if d == nil {
		return nil
	}
	return d.FeatureIds
}

func (d *DtoGetUsageAnalyticsRequest) GetGroupBy() []string {
	if d == nil {
		return nil
	}
	return d.GroupBy
}

func (d *DtoGetUsageAnalyticsRequest) GetPropertyFilters() map[string][]string {
	if d == nil {
		return nil
	}
	return d.PropertyFilters
}

func (d *DtoGetUsageAnalyticsRequest) GetSources() []string {
	if d == nil {
		return nil
	}
	return d.Sources
}

func (d *DtoGetUsageAnalyticsRequest) GetStartTime() *string {
	if d == nil {
		return nil
	}
	return d.StartTime
}

func (d *DtoGetUsageAnalyticsRequest) GetWindowSize() *TypesWindowSize {
	if d == nil {
		return nil
	}
	return d.WindowSize
}
