// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/flexprice/flexprice-go/internal/utils"
)

type DtoSubscriptionPriceCreateRequest struct {
	Amount             *string                 `json:"amount,omitzero"`
	BillingCadence     TypesBillingCadence     `json:"billing_cadence"`
	BillingModel       TypesBillingModel       `json:"billing_model"`
	BillingPeriod      TypesBillingPeriod      `json:"billing_period"`
	BillingPeriodCount *int64                  `json:"billing_period_count,omitzero"`
	Description        *string                 `json:"description,omitzero"`
	DisplayName        *string                 `json:"display_name,omitzero"`
	EndDate            *string                 `json:"end_date,omitzero"`
	FilterValues       map[string][]string     `json:"filter_values,omitzero"`
	InvoiceCadence     TypesInvoiceCadence     `json:"invoice_cadence"`
	LookupKey          *string                 `json:"lookup_key,omitzero"`
	Metadata           map[string]string       `json:"metadata,omitzero"`
	MeterID            *string                 `json:"meter_id,omitzero"`
	MinQuantity        *int64                  `json:"min_quantity,omitzero"`
	PriceUnitConfig    *DtoPriceUnitConfig     `json:"price_unit_config,omitzero"`
	PriceUnitType      TypesPriceUnitType      `json:"price_unit_type"`
	StartDate          *string                 `json:"start_date,omitzero"`
	TierMode           *TypesBillingTier       `json:"tier_mode,omitzero"`
	Tiers              []DtoCreatePriceTier    `json:"tiers,omitzero"`
	TransformQuantity  *PriceTransformQuantity `json:"transform_quantity,omitzero"`
	TrialPeriod        *int64                  `json:"trial_period,omitzero"`
	Type               TypesPriceType          `json:"type"`
}

func (d DtoSubscriptionPriceCreateRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DtoSubscriptionPriceCreateRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DtoSubscriptionPriceCreateRequest) GetAmount() *string {
	if d == nil {
		return nil
	}
	return d.Amount
}

func (d *DtoSubscriptionPriceCreateRequest) GetBillingCadence() TypesBillingCadence {
	if d == nil {
		return TypesBillingCadence("")
	}
	return d.BillingCadence
}

func (d *DtoSubscriptionPriceCreateRequest) GetBillingModel() TypesBillingModel {
	if d == nil {
		return TypesBillingModel("")
	}
	return d.BillingModel
}

func (d *DtoSubscriptionPriceCreateRequest) GetBillingPeriod() TypesBillingPeriod {
	if d == nil {
		return TypesBillingPeriod("")
	}
	return d.BillingPeriod
}

func (d *DtoSubscriptionPriceCreateRequest) GetBillingPeriodCount() *int64 {
	if d == nil {
		return nil
	}
	return d.BillingPeriodCount
}

func (d *DtoSubscriptionPriceCreateRequest) GetDescription() *string {
	if d == nil {
		return nil
	}
	return d.Description
}

func (d *DtoSubscriptionPriceCreateRequest) GetDisplayName() *string {
	if d == nil {
		return nil
	}
	return d.DisplayName
}

func (d *DtoSubscriptionPriceCreateRequest) GetEndDate() *string {
	if d == nil {
		return nil
	}
	return d.EndDate
}

func (d *DtoSubscriptionPriceCreateRequest) GetFilterValues() map[string][]string {
	if d == nil {
		return nil
	}
	return d.FilterValues
}

func (d *DtoSubscriptionPriceCreateRequest) GetInvoiceCadence() TypesInvoiceCadence {
	if d == nil {
		return TypesInvoiceCadence("")
	}
	return d.InvoiceCadence
}

func (d *DtoSubscriptionPriceCreateRequest) GetLookupKey() *string {
	if d == nil {
		return nil
	}
	return d.LookupKey
}

func (d *DtoSubscriptionPriceCreateRequest) GetMetadata() map[string]string {
	if d == nil {
		return nil
	}
	return d.Metadata
}

func (d *DtoSubscriptionPriceCreateRequest) GetMeterID() *string {
	if d == nil {
		return nil
	}
	return d.MeterID
}

func (d *DtoSubscriptionPriceCreateRequest) GetMinQuantity() *int64 {
	if d == nil {
		return nil
	}
	return d.MinQuantity
}

func (d *DtoSubscriptionPriceCreateRequest) GetPriceUnitConfig() *DtoPriceUnitConfig {
	if d == nil {
		return nil
	}
	return d.PriceUnitConfig
}

func (d *DtoSubscriptionPriceCreateRequest) GetPriceUnitType() TypesPriceUnitType {
	if d == nil {
		return TypesPriceUnitType("")
	}
	return d.PriceUnitType
}

func (d *DtoSubscriptionPriceCreateRequest) GetStartDate() *string {
	if d == nil {
		return nil
	}
	return d.StartDate
}

func (d *DtoSubscriptionPriceCreateRequest) GetTierMode() *TypesBillingTier {
	if d == nil {
		return nil
	}
	return d.TierMode
}

func (d *DtoSubscriptionPriceCreateRequest) GetTiers() []DtoCreatePriceTier {
	if d == nil {
		return nil
	}
	return d.Tiers
}

func (d *DtoSubscriptionPriceCreateRequest) GetTransformQuantity() *PriceTransformQuantity {
	if d == nil {
		return nil
	}
	return d.TransformQuantity
}

func (d *DtoSubscriptionPriceCreateRequest) GetTrialPeriod() *int64 {
	if d == nil {
		return nil
	}
	return d.TrialPeriod
}

func (d *DtoSubscriptionPriceCreateRequest) GetType() TypesPriceType {
	if d == nil {
		return TypesPriceType("")
	}
	return d.Type
}
