// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DtoUpdateSubscriptionRequest struct {
	CancelAt          *string `json:"cancel_at,omitzero"`
	CancelAtPeriodEnd *bool   `json:"cancel_at_period_end,omitzero"`
	// ParentSubscriptionID sets or clears the parent subscription. Omit to leave unchanged; send "" to clear.
	ParentSubscriptionID *string                  `json:"parent_subscription_id,omitzero"`
	Status               *TypesSubscriptionStatus `json:"status,omitzero"`
}

func (d *DtoUpdateSubscriptionRequest) GetCancelAt() *string {
	if d == nil {
		return nil
	}
	return d.CancelAt
}

func (d *DtoUpdateSubscriptionRequest) GetCancelAtPeriodEnd() *bool {
	if d == nil {
		return nil
	}
	return d.CancelAtPeriodEnd
}

func (d *DtoUpdateSubscriptionRequest) GetParentSubscriptionID() *string {
	if d == nil {
		return nil
	}
	return d.ParentSubscriptionID
}

func (d *DtoUpdateSubscriptionRequest) GetStatus() *TypesSubscriptionStatus {
	if d == nil {
		return nil
	}
	return d.Status
}
