// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DtoUpdateTaskStatusRequest struct {
	TaskStatus TaskStatus `json:"task_status"`
}

func (d *DtoUpdateTaskStatusRequest) GetTaskStatus() TaskStatus {
	if d == nil {
		return TaskStatus("")
	}
	return d.TaskStatus
}
