// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/flexprice/flexprice-go/internal/utils"
)

type DtoUpdateWalletRequest struct {
	AlertSettings *TypesAlertSettings `json:"alert_settings,omitzero"`
	AutoTopup     *TypesAutoTopup     `json:"auto_topup,omitzero"`
	Config        *TypesWalletConfig  `json:"config,omitzero"`
	Description   *string             `json:"description,omitzero"`
	Metadata      map[string]string   `json:"metadata,omitzero"`
	Name          *string             `json:"name,omitzero"`
}

func (d DtoUpdateWalletRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DtoUpdateWalletRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DtoUpdateWalletRequest) GetAlertSettings() *TypesAlertSettings {
	if d == nil {
		return nil
	}
	return d.AlertSettings
}

func (d *DtoUpdateWalletRequest) GetAutoTopup() *TypesAutoTopup {
	if d == nil {
		return nil
	}
	return d.AutoTopup
}

func (d *DtoUpdateWalletRequest) GetConfig() *TypesWalletConfig {
	if d == nil {
		return nil
	}
	return d.Config
}

func (d *DtoUpdateWalletRequest) GetDescription() *string {
	if d == nil {
		return nil
	}
	return d.Description
}

func (d *DtoUpdateWalletRequest) GetMetadata() map[string]string {
	if d == nil {
		return nil
	}
	return d.Metadata
}

func (d *DtoUpdateWalletRequest) GetName() *string {
	if d == nil {
		return nil
	}
	return d.Name
}
