// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/flexprice/flexprice-go/internal/utils"
)

type FailurePoint struct {
	Error            *ErrorsErrorResponse `json:"error,omitzero"`
	FailurePointType *FailurePointType    `json:"failure_point_type,omitzero"`
}

func (f FailurePoint) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FailurePoint) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FailurePoint) GetError() *ErrorsErrorResponse {
	if f == nil {
		return nil
	}
	return f.Error
}

func (f *FailurePoint) GetFailurePointType() *FailurePointType {
	if f == nil {
		return nil
	}
	return f.FailurePointType
}
