// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/flexprice/flexprice-go/internal/utils"
)

type TypesGroupFilterOrder string

const (
	TypesGroupFilterOrderAsc  TypesGroupFilterOrder = "asc"
	TypesGroupFilterOrderDesc TypesGroupFilterOrder = "desc"
)

func (e TypesGroupFilterOrder) ToPointer() *TypesGroupFilterOrder {
	return &e
}
func (e *TypesGroupFilterOrder) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "asc":
		fallthrough
	case "desc":
		*e = TypesGroupFilterOrder(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TypesGroupFilterOrder: %v", v)
	}
}

type TypesGroupFilter struct {
	EndTime    *string `json:"end_time,omitzero"`
	EntityType *string `json:"entity_type,omitzero"`
	Expand     *string `json:"expand,omitzero"`
	// filters allows complex filtering based on multiple fields
	Filters []TypesFilterCondition `json:"filters,omitzero"`
	// Group specific filters
	GroupIds  []string               `json:"group_ids,omitzero"`
	Limit     *int64                 `json:"limit,omitzero"`
	LookupKey *string                `json:"lookup_key,omitzero"`
	Name      *string                `json:"name,omitzero"`
	Offset    *int64                 `json:"offset,omitzero"`
	Order     *TypesGroupFilterOrder `json:"order,omitzero"`
	Sort      []TypesSortCondition   `json:"sort,omitzero"`
	StartTime *string                `json:"start_time,omitzero"`
	Status    *TypesStatus           `json:"status,omitzero"`
}

func (t TypesGroupFilter) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TypesGroupFilter) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TypesGroupFilter) GetEndTime() *string {
	if t == nil {
		return nil
	}
	return t.EndTime
}

func (t *TypesGroupFilter) GetEntityType() *string {
	if t == nil {
		return nil
	}
	return t.EntityType
}

func (t *TypesGroupFilter) GetExpand() *string {
	if t == nil {
		return nil
	}
	return t.Expand
}

func (t *TypesGroupFilter) GetFilters() []TypesFilterCondition {
	if t == nil {
		return nil
	}
	return t.Filters
}

func (t *TypesGroupFilter) GetGroupIds() []string {
	if t == nil {
		return nil
	}
	return t.GroupIds
}

func (t *TypesGroupFilter) GetLimit() *int64 {
	if t == nil {
		return nil
	}
	return t.Limit
}

func (t *TypesGroupFilter) GetLookupKey() *string {
	if t == nil {
		return nil
	}
	return t.LookupKey
}

func (t *TypesGroupFilter) GetName() *string {
	if t == nil {
		return nil
	}
	return t.Name
}

func (t *TypesGroupFilter) GetOffset() *int64 {
	if t == nil {
		return nil
	}
	return t.Offset
}

func (t *TypesGroupFilter) GetOrder() *TypesGroupFilterOrder {
	if t == nil {
		return nil
	}
	return t.Order
}

func (t *TypesGroupFilter) GetSort() []TypesSortCondition {
	if t == nil {
		return nil
	}
	return t.Sort
}

func (t *TypesGroupFilter) GetStartTime() *string {
	if t == nil {
		return nil
	}
	return t.StartTime
}

func (t *TypesGroupFilter) GetStatus() *TypesStatus {
	if t == nil {
		return nil
	}
	return t.Status
}
