// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type TypesWindowSize string

const (
	TypesWindowSizeMonth      TypesWindowSize = "MONTH"
	TypesWindowSizeMinute     TypesWindowSize = "MINUTE"
	TypesWindowSizeFifteenMin TypesWindowSize = "15MIN"
	TypesWindowSizeThirtyMin  TypesWindowSize = "30MIN"
	TypesWindowSizeHour       TypesWindowSize = "HOUR"
	TypesWindowSizeThreeHour  TypesWindowSize = "3HOUR"
	TypesWindowSizeSixHour    TypesWindowSize = "6HOUR"
	TypesWindowSizeTwelveHour TypesWindowSize = "12HOUR"
	TypesWindowSizeDay        TypesWindowSize = "DAY"
	TypesWindowSizeWeek       TypesWindowSize = "WEEK"
)

func (e TypesWindowSize) ToPointer() *TypesWindowSize {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *TypesWindowSize) IsExact() bool {
	if e != nil {
		switch *e {
		case "MONTH", "MINUTE", "15MIN", "30MIN", "HOUR", "3HOUR", "6HOUR", "12HOUR", "DAY", "WEEK":
			return true
		}
	}
	return false
}
