// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type TypesPaymentTerms string

const (
	TypesPaymentTermsFifteenNet     TypesPaymentTerms = "15 NET"
	TypesPaymentTermsThirtyNet      TypesPaymentTerms = "30 NET"
	TypesPaymentTermsFortyFiveNet   TypesPaymentTerms = "45 NET"
	TypesPaymentTermsSixtyNet       TypesPaymentTerms = "60 NET"
	TypesPaymentTermsSeventyFiveNet TypesPaymentTerms = "75 NET"
	TypesPaymentTermsNinetyNet      TypesPaymentTerms = "90 NET"
)

func (e TypesPaymentTerms) ToPointer() *TypesPaymentTerms {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *TypesPaymentTerms) IsExact() bool {
	if e != nil {
		switch *e {
		case "15 NET", "30 NET", "45 NET", "60 NET", "75 NET", "90 NET":
			return true
		}
	}
	return false
}
