// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type TypesEventProcessingStatusType string

const (
	TypesEventProcessingStatusTypeProcessed  TypesEventProcessingStatusType = "processed"
	TypesEventProcessingStatusTypeProcessing TypesEventProcessingStatusType = "processing"
	TypesEventProcessingStatusTypeFailed     TypesEventProcessingStatusType = "failed"
)

func (e TypesEventProcessingStatusType) ToPointer() *TypesEventProcessingStatusType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *TypesEventProcessingStatusType) IsExact() bool {
	if e != nil {
		switch *e {
		case "processed", "processing", "failed":
			return true
		}
	}
	return false
}
