// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type TypesDebugTrackerStatus string

const (
	TypesDebugTrackerStatusUnprocessed TypesDebugTrackerStatus = "unprocessed"
	TypesDebugTrackerStatusNotFound    TypesDebugTrackerStatus = "not_found"
	TypesDebugTrackerStatusFound       TypesDebugTrackerStatus = "found"
	TypesDebugTrackerStatusError       TypesDebugTrackerStatus = "error"
)

func (e TypesDebugTrackerStatus) ToPointer() *TypesDebugTrackerStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *TypesDebugTrackerStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "unprocessed", "not_found", "found", "error":
			return true
		}
	}
	return false
}
