// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type DtoCreateAPIKeyRequest struct {
	ExpiresAt        *string    `json:"expires_at,omitzero"`
	Name             string     `json:"name"`
	ServiceAccountID *string    `json:"service_account_id,omitzero"`
	Type             SecretType `json:"type"`
}

func (d *DtoCreateAPIKeyRequest) GetExpiresAt() *string {
	if d == nil {
		return nil
	}
	return d.ExpiresAt
}

func (d *DtoCreateAPIKeyRequest) GetName() string {
	if d == nil {
		return ""
	}
	return d.Name
}

func (d *DtoCreateAPIKeyRequest) GetServiceAccountID() *string {
	if d == nil {
		return nil
	}
	return d.ServiceAccountID
}

func (d *DtoCreateAPIKeyRequest) GetType() SecretType {
	if d == nil {
		return SecretType("")
	}
	return d.Type
}
