// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type DtoDeleteCostsheetResponse struct {
	ID      *string `json:"id,omitzero"`
	Message *string `json:"message,omitzero"`
}

func (d *DtoDeleteCostsheetResponse) GetID() *string {
	if d == nil {
		return nil
	}
	return d.ID
}

func (d *DtoDeleteCostsheetResponse) GetMessage() *string {
	if d == nil {
		return nil
	}
	return d.Message
}
