// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/flexprice/flexprice-go/internal/utils"
)

type DtoListCouponsResponse struct {
	Items      []DtoCouponResponse `json:"items,omitzero"`
	Pagination *PaginationResponse `json:"pagination,omitzero"`
}

func (d DtoListCouponsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DtoListCouponsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DtoListCouponsResponse) GetItems() []DtoCouponResponse {
	if d == nil {
		return nil
	}
	return d.Items
}

func (d *DtoListCouponsResponse) GetPagination() *PaginationResponse {
	if d == nil {
		return nil
	}
	return d.Pagination
}
