// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/flexprice/flexprice-go/internal/utils"
)

// DtoSubscriptionChangeRequest - Request object for changing a subscription plan (upgrade/downgrade)
type DtoSubscriptionChangeRequest struct {
	BillingCadence BillingCadence `json:"billing_cadence"`
	BillingCycle   BillingCycle   `json:"billing_cycle"`
	BillingPeriod  BillingPeriod  `json:"billing_period"`
	// billing_period_count is the billing period count for the new subscription
	BillingPeriodCount *int64        `json:"billing_period_count,omitzero"`
	ChangeAt           *ScheduleType `json:"change_at,omitzero"`
	// metadata contains additional key-value pairs for storing extra information
	Metadata          map[string]string `json:"metadata,omitzero"`
	ProrationBehavior ProrationBehavior `json:"proration_behavior"`
	// target_plan_id is the ID of the new plan to change to (required)
	TargetPlanID string `json:"target_plan_id"`
}

func (d DtoSubscriptionChangeRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DtoSubscriptionChangeRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DtoSubscriptionChangeRequest) GetBillingCadence() BillingCadence {
	if d == nil {
		return BillingCadence("")
	}
	return d.BillingCadence
}

func (d *DtoSubscriptionChangeRequest) GetBillingCycle() BillingCycle {
	if d == nil {
		return BillingCycle("")
	}
	return d.BillingCycle
}

func (d *DtoSubscriptionChangeRequest) GetBillingPeriod() BillingPeriod {
	if d == nil {
		return BillingPeriod("")
	}
	return d.BillingPeriod
}

func (d *DtoSubscriptionChangeRequest) GetBillingPeriodCount() *int64 {
	if d == nil {
		return nil
	}
	return d.BillingPeriodCount
}

func (d *DtoSubscriptionChangeRequest) GetChangeAt() *ScheduleType {
	if d == nil {
		return nil
	}
	return d.ChangeAt
}

func (d *DtoSubscriptionChangeRequest) GetMetadata() map[string]string {
	if d == nil {
		return nil
	}
	return d.Metadata
}

func (d *DtoSubscriptionChangeRequest) GetProrationBehavior() ProrationBehavior {
	if d == nil {
		return ProrationBehavior("")
	}
	return d.ProrationBehavior
}

func (d *DtoSubscriptionChangeRequest) GetTargetPlanID() string {
	if d == nil {
		return ""
	}
	return d.TargetPlanID
}
