// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type DtoUpdateScheduledTaskRequest struct {
	Enabled bool `json:"enabled"`
}

func (d *DtoUpdateScheduledTaskRequest) GetEnabled() bool {
	if d == nil {
		return false
	}
	return d.Enabled
}
