// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type PaginationResponse struct {
	Limit  *int64 `json:"limit,omitzero"`
	Offset *int64 `json:"offset,omitzero"`
	Total  *int64 `json:"total,omitzero"`
}

func (p *PaginationResponse) GetLimit() *int64 {
	if p == nil {
		return nil
	}
	return p.Limit
}

func (p *PaginationResponse) GetOffset() *int64 {
	if p == nil {
		return nil
	}
	return p.Offset
}

func (p *PaginationResponse) GetTotal() *int64 {
	if p == nil {
		return nil
	}
	return p.Total
}
