// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"encoding/json"
	"fmt"
	"github.com/flexprice/flexprice-go/internal/utils"
)

type PlanFilterOrder string

const (
	PlanFilterOrderAsc  PlanFilterOrder = "asc"
	PlanFilterOrderDesc PlanFilterOrder = "desc"
)

func (e PlanFilterOrder) ToPointer() *PlanFilterOrder {
	return &e
}
func (e *PlanFilterOrder) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "asc":
		fallthrough
	case "desc":
		*e = PlanFilterOrder(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PlanFilterOrder: %v", v)
	}
}

type PlanFilter struct {
	EndTime *string `json:"end_time,omitzero"`
	Expand  *string `json:"expand,omitzero"`
	// filters allows complex filtering based on multiple fields
	Filters   []FilterCondition `json:"filters,omitzero"`
	Limit     *int64            `json:"limit,omitzero"`
	LookupKey *string           `json:"lookup_key,omitzero"`
	Offset    *int64            `json:"offset,omitzero"`
	Order     *PlanFilterOrder  `json:"order,omitzero"`
	PlanIds   []string          `json:"plan_ids,omitzero"`
	Sort      []SortCondition   `json:"sort,omitzero"`
	StartTime *string           `json:"start_time,omitzero"`
	Status    *Status           `json:"status,omitzero"`
}

func (p PlanFilter) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PlanFilter) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PlanFilter) GetEndTime() *string {
	if p == nil {
		return nil
	}
	return p.EndTime
}

func (p *PlanFilter) GetExpand() *string {
	if p == nil {
		return nil
	}
	return p.Expand
}

func (p *PlanFilter) GetFilters() []FilterCondition {
	if p == nil {
		return nil
	}
	return p.Filters
}

func (p *PlanFilter) GetLimit() *int64 {
	if p == nil {
		return nil
	}
	return p.Limit
}

func (p *PlanFilter) GetLookupKey() *string {
	if p == nil {
		return nil
	}
	return p.LookupKey
}

func (p *PlanFilter) GetOffset() *int64 {
	if p == nil {
		return nil
	}
	return p.Offset
}

func (p *PlanFilter) GetOrder() *PlanFilterOrder {
	if p == nil {
		return nil
	}
	return p.Order
}

func (p *PlanFilter) GetPlanIds() []string {
	if p == nil {
		return nil
	}
	return p.PlanIds
}

func (p *PlanFilter) GetSort() []SortCondition {
	if p == nil {
		return nil
	}
	return p.Sort
}

func (p *PlanFilter) GetStartTime() *string {
	if p == nil {
		return nil
	}
	return p.StartTime
}

func (p *PlanFilter) GetStatus() *Status {
	if p == nil {
		return nil
	}
	return p.Status
}
