// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type ScheduledTaskInterval string

const (
	ScheduledTaskIntervalFifteenMin ScheduledTaskInterval = "15MIN"
	ScheduledTaskIntervalCustom     ScheduledTaskInterval = "custom"
	ScheduledTaskIntervalHourly     ScheduledTaskInterval = "hourly"
	ScheduledTaskIntervalDaily      ScheduledTaskInterval = "daily"
)

func (e ScheduledTaskInterval) ToPointer() *ScheduledTaskInterval {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ScheduledTaskInterval) IsExact() bool {
	if e != nil {
		switch *e {
		case "15MIN", "custom", "hourly", "daily":
			return true
		}
	}
	return false
}
