// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type TimeRangeFilter struct {
	EndTime   *string `json:"end_time,omitzero"`
	StartTime *string `json:"start_time,omitzero"`
}

func (t *TimeRangeFilter) GetEndTime() *string {
	if t == nil {
		return nil
	}
	return t.EndTime
}

func (t *TimeRangeFilter) GetStartTime() *string {
	if t == nil {
		return nil
	}
	return t.StartTime
}
