// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package errors

import (
	"encoding/json"
	"github.com/flexprice/flexprice-go/types"
)

type ErrorsErrorResponse struct {
	Error_   *types.ErrorsErrorDetail `json:"error,omitzero"`
	Success  *bool                    `json:"success,omitzero"`
	HTTPMeta types.HTTPMetadata       `json:"-"`
}

var _ error = &ErrorsErrorResponse{}

func (e *ErrorsErrorResponse) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
